// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class VwActiveAlarm
{
    public Guid OrganizationId { get; set; }

    public Guid AlarmId { get; set; }

    public Guid StationId { get; set; }

    public string StationCode { get; set; }

    public string StationName { get; set; }

    public string RegionName { get; set; }

    public string AlarmType { get; set; }

    public string AlarmTypeName { get; set; }

    public int? ParameterId { get; set; }

    public string ParameterCode { get; set; }

    public string Severity { get; set; }

    public string Status { get; set; }

    public string Message { get; set; }

    public decimal? ValueAtRaise { get; set; }

    public decimal? ThresholdValue { get; set; }

    public DateTime RaisedAtUtc { get; set; }

    public DateTime? AcknowledgedAtUtc { get; set; }

    public string AcknowledgedBy { get; set; }

    public int? MinutesToAcknowledge { get; set; }
}