// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class VwCurrentTelemetry
{
    public Guid OrganizationId { get; set; }

    public Guid StationId { get; set; }

    public string StationCode { get; set; }

    public string StationName { get; set; }

    public int ParameterId { get; set; }

    public string ParameterCode { get; set; }

    public string ParameterName { get; set; }

    public string CanonicalUnit { get; set; }

    public DateTime TimestampUtc { get; set; }

    public decimal? Value { get; set; }

    public string QualityFlag { get; set; }

    public bool IsInterpolated { get; set; }
}