// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class VwModelHealth
{
    public Guid OrganizationId { get; set; }

    public Guid ModelId { get; set; }

    public string ModelType { get; set; }

    public Guid? StationId { get; set; }

    public string StationCode { get; set; }

    public int? ParameterId { get; set; }

    public string ParameterCode { get; set; }

    public string Version { get; set; }

    public string Status { get; set; }

    public DateTime? TrainedAtUtc { get; set; }

    public DateTime? PromotedAtUtc { get; set; }

    public string FeatureSetVersion { get; set; }

    public string CleaningRulesetVersion { get; set; }

    public string MetricsJson { get; set; }

    public int? TrainingRunCount { get; set; }

    public DateTime? LastTrainingFinishedAtUtc { get; set; }
}