// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class VwOrganizationKpi
{
    public Guid OrganizationId { get; set; }

    public string OrganizationName { get; set; }

    public int? TotalStations { get; set; }

    public int? OnlineStations { get; set; }

    public int? OfflineStations { get; set; }

    public int? OpenAlarms { get; set; }

    public int? CriticalAlarms { get; set; }

    public int? WarningAlarms { get; set; }
}