// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class VwStationDirectory
{
    public Guid OrganizationId { get; set; }

    public string OrganizationName { get; set; }

    public Guid? RegionId { get; set; }

    public string RegionName { get; set; }

    public Guid StationId { get; set; }

    public string StationCode { get; set; }

    public string StationName { get; set; }

    public string Status { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public DateTime? LastSeenAtUtc { get; set; }

    public int? EnabledParameterCount { get; set; }

    public int? OpenAlarmCount { get; set; }

    public int? CriticalAlarmCount { get; set; }
}