// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class DataQualityLog
{
    public long DataQualityLogId { get; set; }

    public Guid OrganizationId { get; set; }

    public Guid StationId { get; set; }

    public DateTime WindowStartUtc { get; set; }

    public DateTime WindowEndUtc { get; set; }

    public int TotalCount { get; set; }

    public int ValidCount { get; set; }

    public int InterpolatedCount { get; set; }

    public int QuarantinedCount { get; set; }

    public int DuplicateCount { get; set; }

    public decimal ValidPct { get; set; }

    public decimal InterpolatedPct { get; set; }

    public decimal QuarantinedPct { get; set; }

    public int SchemaDriftEvents { get; set; }

    public string RulesetVersion { get; set; }

    public DateTime ComputedAtUtc { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual Station Station { get; set; }
}