// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class FeatureStoreEntry
{
    public long FeatureStoreEntryId { get; set; }

    public Guid OrganizationId { get; set; }

    public Guid StationId { get; set; }

    public int ParameterId { get; set; }

    public DateTime TimestampUtc { get; set; }

    public string FeatureSetVersion { get; set; }

    public string FeaturesJson { get; set; }

    public string SourceQualitySummary { get; set; }

    public DateTime ComputedAtUtc { get; set; }

    public virtual FeatureSet FeatureSetVersionNavigation { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual StationParameter StationParameter { get; set; }
}