// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class FeatureSet
{
    public string FeatureSetVersion { get; set; }

    public string Name { get; set; }

    public string DefinitionJson { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<FeatureStoreEntry> FeatureStoreEntries { get; set; } = new List<FeatureStoreEntry>();

    public virtual ICollection<MlModel> MlModels { get; set; } = new List<MlModel>();

    public virtual ICollection<MlTrainingRun> MlTrainingRuns { get; set; } = new List<MlTrainingRun>();
}