// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class IngestionBatch
{
    public Guid IngestionBatchId { get; set; }

    public Guid OrganizationId { get; set; }

    public string SourceType { get; set; }

    public string SourceName { get; set; }

    public string SchemaVersion { get; set; }

    public DateTime StartedAtUtc { get; set; }

    public DateTime? CompletedAtUtc { get; set; }

    public int TotalRows { get; set; }

    public int AcceptedRows { get; set; }

    public int RejectedRows { get; set; }

    public string Status { get; set; }

    public string ErrorMessage { get; set; }

    public virtual ICollection<MeasurementRaw> MeasurementRaws { get; set; } = new List<MeasurementRaw>();

    public virtual Organization Organization { get; set; }
}