// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class MeasurementRaw
{
    public long MeasurementRawId { get; set; }

    public Guid OrganizationId { get; set; }

    public Guid StationId { get; set; }

    public int ParameterId { get; set; }

    public Guid? IngestionBatchId { get; set; }

    public DateTime DeviceTimestampUtc { get; set; }

    public DateTime IngestionTimestampUtc { get; set; }

    public decimal? RawValue { get; set; }

    public string RawUnit { get; set; }

    public string PayloadJson { get; set; }

    public long? DeviceSequence { get; set; }

    public long? DuplicateOfId { get; set; }

    public bool IsDuplicate { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual MeasurementRaw DuplicateOf { get; set; }

    public virtual IngestionBatch IngestionBatch { get; set; }

    public virtual ICollection<MeasurementRaw> InverseDuplicateOf { get; set; } = new List<MeasurementRaw>();

    public virtual ICollection<MeasurementClean> MeasurementCleans { get; set; } = new List<MeasurementClean>();

    public virtual Organization Organization { get; set; }

    public virtual StationParameter StationParameter { get; set; }
}