// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class MeasurementClean
{
    public long MeasurementCleanId { get; set; }

    public Guid OrganizationId { get; set; }

    public Guid StationId { get; set; }

    public int ParameterId { get; set; }

    public long? SourceRawId { get; set; }

    public DateTime TimestampUtc { get; set; }

    public decimal? Value { get; set; }

    public string CanonicalUnit { get; set; }

    public string QualityFlag { get; set; }

    public string QuarantineReason { get; set; }

    public string CleaningRulesetVersion { get; set; }

    public bool IsInterpolated { get; set; }

    public bool IsGapBoundary { get; set; }

    public DateTime ProcessedAtUtc { get; set; }

    public virtual ICollection<AnomalyEvent> AnomalyEvents { get; set; } = new List<AnomalyEvent>();

    public virtual Organization Organization { get; set; }

    public virtual MeasurementRaw SourceRaw { get; set; }

    public virtual StationParameter StationParameter { get; set; }
}