// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class DashboardLayout
{
    public long DashboardLayoutId { get; set; }

    public Guid UserId { get; set; }

    public string LayoutName { get; set; }

    public string WidgetsJson { get; set; }

    public bool IsDefault { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    public virtual User User { get; set; }
}