// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class Organization
{
    public Guid OrganizationId { get; set; }

    public string Name { get; set; }

    public string Slug { get; set; }

    public string LogoUrl { get; set; }

    public string PrimaryColor { get; set; }

    public string DefaultTimeZone { get; set; }

    public string DefaultLocale { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    public virtual ICollection<Alarm> Alarms { get; set; } = new List<Alarm>();

    public virtual ICollection<AnomalyEvent> AnomalyEvents { get; set; } = new List<AnomalyEvent>();

    public virtual ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();

    public virtual ICollection<ChartAnnotation> ChartAnnotations { get; set; } = new List<ChartAnnotation>();

    public virtual ICollection<DataQualityLog> DataQualityLogs { get; set; } = new List<DataQualityLog>();

    public virtual ICollection<FeatureStoreEntry> FeatureStoreEntries { get; set; } = new List<FeatureStoreEntry>();

    public virtual ICollection<FocusStationScore> FocusStationScores { get; set; } = new List<FocusStationScore>();

    public virtual ICollection<IngestionBatch> IngestionBatches { get; set; } = new List<IngestionBatch>();

    public virtual ICollection<MeasurementClean> MeasurementCleans { get; set; } = new List<MeasurementClean>();

    public virtual ICollection<MeasurementRaw> MeasurementRaws { get; set; } = new List<MeasurementRaw>();

    public virtual ICollection<MlModel> MlModels { get; set; } = new List<MlModel>();

    public virtual ICollection<MlTrainingRun> MlTrainingRuns { get; set; } = new List<MlTrainingRun>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<Region> Regions { get; set; } = new List<Region>();

    public virtual ICollection<ReportSchedule> ReportSchedules { get; set; } = new List<ReportSchedule>();

    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    public virtual ICollection<RiskScore> RiskScores { get; set; } = new List<RiskScore>();

    public virtual ICollection<ShareSnapshot> ShareSnapshots { get; set; } = new List<ShareSnapshot>();

    public virtual ICollection<StationCluster> StationClusters { get; set; } = new List<StationCluster>();

    public virtual ICollection<StationCollaborationNote> StationCollaborationNotes
    {
        get;
        set;
    } = new List<StationCollaborationNote>();

    public virtual ICollection<StationLink> StationLinks { get; set; } = new List<StationLink>();

    public virtual ICollection<Station> Stations { get; set; } = new List<Station>();

    public virtual ICollection<SystemSetting> SystemSettings { get; set; } = new List<SystemSetting>();

    public virtual ICollection<Threshold> Thresholds { get; set; } = new List<Threshold>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}
