// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class ShareSnapshot
{
    public Guid ShareSnapshotId { get; set; }

    public Guid OrganizationId { get; set; }

    public Guid CreatedByUserId { get; set; }

    public Guid? StationId { get; set; }

    public string SnapshotJson { get; set; }

    public string TokenHash { get; set; }

    public DateTime ExpiresAtUtc { get; set; }

    public DateTime? RevokedAtUtc { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual Station Station { get; set; }
}