// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class SystemSetting
{
    public long SystemSettingId { get; set; }

    public Guid? OrganizationId { get; set; }

    public string SettingKey { get; set; }

    public string SettingValue { get; set; }

    public string ValueType { get; set; }

    public bool IsSecret { get; set; }

    public Guid? UpdatedByUserId { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    public virtual Organization Organization { get; set; }
}