// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class ReportSchedule
{
    public long ReportScheduleId { get; set; }

    public Guid OrganizationId { get; set; }

    public Guid CreatedByUserId { get; set; }

    public Guid? StationId { get; set; }

    public int? ParameterId { get; set; }

    public string Frequency { get; set; }

    public string Format { get; set; }

    public string RecipientJson { get; set; }

    public DateTime NextRunAtUtc { get; set; }

    public DateTime? LastRunAtUtc { get; set; }

    public bool IsActive { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual Parameter Parameter { get; set; }

    public virtual Station Station { get; set; }
}