// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class Report
{
    public Guid ReportId { get; set; }

    public Guid OrganizationId { get; set; }

    public Guid RequestedByUserId { get; set; }

    public Guid? StationId { get; set; }

    public int? ParameterId { get; set; }

    public DateTime PeriodStartUtc { get; set; }

    public DateTime PeriodEndUtc { get; set; }

    public string Format { get; set; }

    public string Status { get; set; }

    public string FilePath { get; set; }

    public string SummaryJson { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? CompletedAtUtc { get; set; }

    public string ErrorMessage { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual Parameter Parameter { get; set; }

    public virtual User RequestedByUser { get; set; }

    public virtual Station Station { get; set; }
}