using AutoMapper;
using WaterOperations.Application.Features.Auth.DTOs;
using WaterOperations.Domain.Entities;

namespace WaterOperations.Application.Features.Auth.Mapping;

/// <summary>
/// AutoMapper profile for authentication DTOs.
///
/// <see cref="AuthResponse"/> (JWT + refresh token) is generated by the token service,
/// not projected from an EF entity. Only the <see cref="Session"/> → <see cref="RefreshRequest"/>
/// mapping is registered here for introspection / session rotation use cases.
/// </summary>
public sealed class AuthMappingProfile : Profile
{
    public AuthMappingProfile()
    {
        // Session → RefreshRequest (used when rotating refresh tokens)
        CreateMap<Session, RefreshRequest>()
            .ForMember(dest => dest.RefreshToken,
                opt => opt.MapFrom(src => src.RefreshTokenHash));
    }
}
