CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'Operations') THEN
        CREATE SCHEMA "Operations";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'AI') THEN
        CREATE SCHEMA "AI";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'Security') THEN
        CREATE SCHEMA "Security";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'Platform') THEN
        CREATE SCHEMA "Platform";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'Telemetry') THEN
        CREATE SCHEMA "Telemetry";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'Core') THEN
        CREATE SCHEMA "Core";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'Reporting') THEN
        CREATE SCHEMA "Reporting";
    END IF;
END $EF$;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE "Operations"."AlarmType" (
    "AlarmTypeId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(60) NOT NULL,
    "Name" character varying(150) NOT NULL,
    "Description" character varying(500),
    CONSTRAINT "PK_AlarmType" PRIMARY KEY ("AlarmTypeId")
);

CREATE TABLE "Telemetry"."FeatureSet" (
    "FeatureSetVersion" character varying(50) NOT NULL,
    "Name" character varying(150) NOT NULL,
    "DefinitionJson" text NOT NULL,
    "CreatedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_FeatureSet" PRIMARY KEY ("FeatureSetVersion")
);

CREATE TABLE "Platform"."Organization" (
    "OrganizationId" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "Name" character varying(200) NOT NULL,
    "Slug" character varying(120) NOT NULL,
    "LogoUrl" character varying(500),
    "PrimaryColor" character varying(20),
    "DefaultTimeZone" character varying(100) NOT NULL DEFAULT 'UTC',
    "DefaultLocale" character varying(10) NOT NULL DEFAULT 'en',
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    "UpdatedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT "PK_Organization" PRIMARY KEY ("OrganizationId")
);

CREATE TABLE "Core"."Parameter" (
    "ParameterId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(50) NOT NULL,
    "Name" character varying(150) NOT NULL,
    "CanonicalUnit" character varying(32) NOT NULL,
    "DataType" character varying(20) NOT NULL DEFAULT 'DECIMAL',
    "MinimumValue" numeric(18,6),
    "MaximumValue" numeric(18,6),
    "DefaultResampleMinutes" integer NOT NULL DEFAULT 15,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_Parameter" PRIMARY KEY ("ParameterId")
);

CREATE TABLE "Security"."Permission" (
    "PermissionId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(100) NOT NULL,
    "DisplayName" character varying(150) NOT NULL,
    CONSTRAINT "PK_Permission" PRIMARY KEY ("PermissionId")
);

CREATE TABLE "Security"."Role" (
    "RoleId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(50) NOT NULL,
    "DisplayName" character varying(100) NOT NULL,
    "IsSystemRole" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_Role" PRIMARY KEY ("RoleId")
);

CREATE TABLE "Telemetry"."IngestionBatch" (
    "IngestionBatchId" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "OrganizationId" uuid NOT NULL,
    "SourceType" character varying(30) NOT NULL DEFAULT 'DEVICE',
    "SourceName" character varying(200),
    "SchemaVersion" character varying(50),
    "StartedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    "CompletedAtUtc" timestamp(3) with time zone,
    "TotalRows" integer NOT NULL,
    "AcceptedRows" integer NOT NULL,
    "RejectedRows" integer NOT NULL,
    "Status" character varying(20) NOT NULL DEFAULT 'RECEIVED',
    "ErrorMessage" character varying(2000),
    CONSTRAINT "PK_IngestionBatch" PRIMARY KEY ("IngestionBatchId"),
    CONSTRAINT "FK_IngestionBatch_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId")
);

CREATE TABLE "Core"."Region" (
    "RegionId" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "OrganizationId" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Code" character varying(50) NOT NULL,
    "Description" character varying(1000),
    "BoundaryJson" text,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT "PK_Region" PRIMARY KEY ("RegionId"),
    CONSTRAINT "FK_Region_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId") ON DELETE CASCADE
);

CREATE TABLE "Platform"."SystemSetting" (
    "SystemSettingId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" uuid,
    "SettingKey" character varying(150) NOT NULL,
    "SettingValue" text NOT NULL,
    "ValueType" character varying(20) NOT NULL DEFAULT 'STRING',
    "IsSecret" boolean NOT NULL,
    "UpdatedByUserId" uuid,
    "UpdatedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT "PK_SystemSetting" PRIMARY KEY ("SystemSettingId"),
    CONSTRAINT "FK_SystemSetting_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId")
);

CREATE TABLE "Security"."User" (
    "UserId" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "OrganizationId" uuid NOT NULL,
    "Email" character varying(320) NOT NULL,
    "DisplayName" character varying(200) NOT NULL,
    "PasswordHash" character varying(500) NOT NULL,
    "ClientType" character varying(20) NOT NULL DEFAULT 'WEB',
    "PreferredLocale" character varying(10) NOT NULL DEFAULT 'en',
    "PreferredTimeZone" character varying(100) NOT NULL DEFAULT 'UTC',
    "Theme" character varying(20) NOT NULL DEFAULT 'LIGHT',
    "DecimalPrecision" smallint NOT NULL DEFAULT 2,
    "IsMfaEnabled" boolean NOT NULL,
    "MfaSecretEncrypted" bytea,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "LastLoginAtUtc" timestamp(3) with time zone,
    "CreatedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    "UpdatedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    "RowVersion" bytea NOT NULL,
    CONSTRAINT "PK_User" PRIMARY KEY ("UserId"),
    CONSTRAINT "FK_User_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId")
);

CREATE TABLE "Security"."RolePermission" (
    "RoleId" integer NOT NULL,
    "PermissionId" integer NOT NULL,
    CONSTRAINT "PK_RolePermission" PRIMARY KEY ("RoleId", "PermissionId"),
    CONSTRAINT "FK_RolePermission_Permission" FOREIGN KEY ("PermissionId") REFERENCES "Security"."Permission" ("PermissionId") ON DELETE CASCADE,
    CONSTRAINT "FK_RolePermission_Role" FOREIGN KEY ("RoleId") REFERENCES "Security"."Role" ("RoleId") ON DELETE CASCADE
);

CREATE TABLE "Core"."Station" (
    "StationId" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "OrganizationId" uuid NOT NULL,
    "RegionId" uuid,
    "StationCode" character varying(80) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(1000),
    "Latitude" numeric(9,6),
    "Longitude" numeric(9,6),
    "ElevationMeters" numeric(10,3),
    "StaffGaugeHeight" numeric(18,4),
    "Status" character varying(20) NOT NULL DEFAULT 'OFFLINE',
    "LastSeenAtUtc" timestamp(3) with time zone,
    "CommunicationIntervalSeconds" integer,
    "MetadataJson" text,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    "UpdatedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT "PK_Station" PRIMARY KEY ("StationId"),
    CONSTRAINT "FK_Station_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId") ON DELETE CASCADE,
    CONSTRAINT "FK_Station_Region" FOREIGN KEY ("RegionId") REFERENCES "Core"."Region" ("RegionId")
);

CREATE TABLE "Security"."AuditLog" (
    "AuditLogId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" uuid,
    "ActorUserId" uuid,
    "ActionCode" character varying(100) NOT NULL,
    "EntityType" character varying(100),
    "EntityId" character varying(100),
    "RequestId" character varying(100),
    "IpAddress" character varying(45),
    "Success" boolean NOT NULL DEFAULT TRUE,
    "BeforeJson" text,
    "AfterJson" text,
    "MetadataJson" text,
    "OccurredAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT "PK_AuditLog" PRIMARY KEY ("AuditLogId"),
    CONSTRAINT "FK_Audit_Actor" FOREIGN KEY ("ActorUserId") REFERENCES "Security"."User" ("UserId"),
    CONSTRAINT "FK_Audit_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId")
);

CREATE TABLE "Platform"."DashboardLayout" (
    "DashboardLayoutId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "LayoutName" character varying(100) NOT NULL DEFAULT 'Default',
    "WidgetsJson" text NOT NULL,
    "IsDefault" boolean NOT NULL,
    "UpdatedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT "PK_DashboardLayout" PRIMARY KEY ("DashboardLayoutId"),
    CONSTRAINT "FK_DashboardLayout_User" FOREIGN KEY ("UserId") REFERENCES "Security"."User" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Operations"."NotificationPreference" (
    "UserId" uuid NOT NULL,
    "Severity" character varying(20) NOT NULL,
    "InAppEnabled" boolean NOT NULL DEFAULT TRUE,
    "EmailEnabled" boolean NOT NULL,
    "PushEnabled" boolean NOT NULL,
    "DesktopEnabled" boolean NOT NULL DEFAULT TRUE,
    "DailyDigestEnabled" boolean NOT NULL,
    CONSTRAINT "PK_NotificationPreference" PRIMARY KEY ("UserId", "Severity"),
    CONSTRAINT "FK_NotificationPreference_User" FOREIGN KEY ("UserId") REFERENCES "Security"."User" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Security"."Session" (
    "SessionId" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "UserId" uuid NOT NULL,
    "RefreshTokenHash" character varying(500) NOT NULL,
    "DeviceName" character varying(200),
    "IpAddress" character varying(45),
    "UserAgent" character varying(1000),
    "CreatedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    "ExpiresAtUtc" timestamp(3) with time zone NOT NULL,
    "RevokedAtUtc" timestamp(3) with time zone,
    CONSTRAINT "PK_Session" PRIMARY KEY ("SessionId"),
    CONSTRAINT "FK_Session_User" FOREIGN KEY ("UserId") REFERENCES "Security"."User" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Security"."UserRole" (
    "UserId" uuid NOT NULL,
    "RoleId" integer NOT NULL,
    "AssignedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    "AssignedByUserId" uuid,
    CONSTRAINT "PK_UserRole" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRole_AssignedBy" FOREIGN KEY ("AssignedByUserId") REFERENCES "Security"."User" ("UserId"),
    CONSTRAINT "FK_UserRole_Role" FOREIGN KEY ("RoleId") REFERENCES "Security"."Role" ("RoleId"),
    CONSTRAINT "FK_UserRole_User" FOREIGN KEY ("UserId") REFERENCES "Security"."User" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Operations"."Alarm" (
    "AlarmId" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "OrganizationId" uuid NOT NULL,
    "StationId" uuid NOT NULL,
    "ParameterId" integer,
    "AlarmTypeId" integer NOT NULL,
    "Severity" character varying(20) NOT NULL,
    "Status" character varying(20) NOT NULL DEFAULT 'ACTIVE',
    "Message" character varying(1000) NOT NULL,
    "ValueAtRaise" numeric(38,12),
    "ThresholdValue" numeric(38,12),
    "RaisedAtUtc" timestamp(3) with time zone NOT NULL,
    "AcknowledgedAtUtc" timestamp(3) with time zone,
    "AcknowledgedByUserId" uuid,
    "ResolvedAtUtc" timestamp(3) with time zone,
    "ResolvedByUserId" uuid,
    "ResolutionNote" character varying(2000),
    "CorrelationClusterId" uuid,
    "CreatedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT "PK_Alarm" PRIMARY KEY ("AlarmId"),
    CONSTRAINT "FK_Alarm_AckUser" FOREIGN KEY ("AcknowledgedByUserId") REFERENCES "Security"."User" ("UserId"),
    CONSTRAINT "FK_Alarm_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId") ON DELETE CASCADE,
    CONSTRAINT "FK_Alarm_Parameter" FOREIGN KEY ("ParameterId") REFERENCES "Core"."Parameter" ("ParameterId"),
    CONSTRAINT "FK_Alarm_ResolveUser" FOREIGN KEY ("ResolvedByUserId") REFERENCES "Security"."User" ("UserId"),
    CONSTRAINT "FK_Alarm_Station" FOREIGN KEY ("StationId") REFERENCES "Core"."Station" ("StationId"),
    CONSTRAINT "FK_Alarm_Type" FOREIGN KEY ("AlarmTypeId") REFERENCES "Operations"."AlarmType" ("AlarmTypeId")
);

CREATE TABLE "Operations"."ChartAnnotation" (
    "ChartAnnotationId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" uuid NOT NULL,
    "StationId" uuid NOT NULL,
    "ParameterId" integer,
    "UserId" uuid NOT NULL,
    "TimestampUtc" timestamp(3) with time zone NOT NULL,
    "Text" character varying(2000) NOT NULL,
    "CreatedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    "UpdatedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT "PK_ChartAnnotation" PRIMARY KEY ("ChartAnnotationId"),
    CONSTRAINT "FK_Annotation_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId"),
    CONSTRAINT "FK_Annotation_Parameter" FOREIGN KEY ("ParameterId") REFERENCES "Core"."Parameter" ("ParameterId"),
    CONSTRAINT "FK_Annotation_Station" FOREIGN KEY ("StationId") REFERENCES "Core"."Station" ("StationId"),
    CONSTRAINT "FK_Annotation_User" FOREIGN KEY ("UserId") REFERENCES "Security"."User" ("UserId")
);

CREATE TABLE "Telemetry"."DataQualityLog" (
    "DataQualityLogId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" uuid NOT NULL,
    "StationId" uuid NOT NULL,
    "WindowStartUtc" timestamp(3) with time zone NOT NULL,
    "WindowEndUtc" timestamp(3) with time zone NOT NULL,
    "TotalCount" integer NOT NULL,
    "ValidCount" integer NOT NULL,
    "InterpolatedCount" integer NOT NULL,
    "QuarantinedCount" integer NOT NULL,
    "DuplicateCount" integer NOT NULL,
    "ValidPct" numeric(7,3) NOT NULL,
    "InterpolatedPct" numeric(7,3) NOT NULL,
    "QuarantinedPct" numeric(7,3) NOT NULL,
    "SchemaDriftEvents" integer NOT NULL,
    "RulesetVersion" character varying(50),
    "ComputedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT "PK_DataQualityLog" PRIMARY KEY ("DataQualityLogId"),
    CONSTRAINT "FK_DQ_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId"),
    CONSTRAINT "FK_DQ_Station" FOREIGN KEY ("StationId") REFERENCES "Core"."Station" ("StationId")
);

CREATE TABLE "AI"."FocusStationScore" (
    "FocusStationScoreId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "StationId" uuid NOT NULL,
    "Score" numeric(12,6) NOT NULL,
    "RankNo" integer,
    "ReasonsJson" text,
    "ComputedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    "IsPinned" boolean NOT NULL,
    CONSTRAINT "PK_FocusStationScore" PRIMARY KEY ("FocusStationScoreId"),
    CONSTRAINT "FK_FocusScore_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId"),
    CONSTRAINT "FK_FocusScore_Station" FOREIGN KEY ("StationId") REFERENCES "Core"."Station" ("StationId"),
    CONSTRAINT "FK_FocusScore_User" FOREIGN KEY ("UserId") REFERENCES "Security"."User" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "AI"."MlModel" (
    "ModelId" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "OrganizationId" uuid NOT NULL,
    "ModelType" character varying(50) NOT NULL,
    "StationId" uuid,
    "ParameterId" integer,
    "Version" character varying(50) NOT NULL,
    "Status" character varying(20) NOT NULL DEFAULT 'TRAINING',
    "TrainedAtUtc" timestamp(3) with time zone,
    "PromotedAtUtc" timestamp(3) with time zone,
    "MetricsJson" text,
    "ArtifactPath" character varying(1000),
    "ArtifactSha256" character varying(64),
    "FeatureSetVersion" character varying(50),
    "CleaningRulesetVersion" character varying(50),
    "HyperparametersJson" text,
    "CreatedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT "PK_MlModel" PRIMARY KEY ("ModelId"),
    CONSTRAINT "FK_MlModel_FeatureSet" FOREIGN KEY ("FeatureSetVersion") REFERENCES "Telemetry"."FeatureSet" ("FeatureSetVersion"),
    CONSTRAINT "FK_MlModel_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId"),
    CONSTRAINT "FK_MlModel_Parameter" FOREIGN KEY ("ParameterId") REFERENCES "Core"."Parameter" ("ParameterId"),
    CONSTRAINT "FK_MlModel_Station" FOREIGN KEY ("StationId") REFERENCES "Core"."Station" ("StationId")
);

CREATE TABLE "Reporting"."Report" (
    "ReportId" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "OrganizationId" uuid NOT NULL,
    "RequestedByUserId" uuid NOT NULL,
    "StationId" uuid,
    "ParameterId" integer,
    "PeriodStartUtc" timestamp(3) with time zone NOT NULL,
    "PeriodEndUtc" timestamp(3) with time zone NOT NULL,
    "Format" character varying(20) NOT NULL DEFAULT 'PDF',
    "Status" character varying(20) NOT NULL DEFAULT 'QUEUED',
    "FilePath" character varying(1000),
    "SummaryJson" text,
    "CreatedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    "CompletedAtUtc" timestamp(3) with time zone,
    "ErrorMessage" character varying(2000),
    CONSTRAINT "PK_Report" PRIMARY KEY ("ReportId"),
    CONSTRAINT "FK_Report_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId"),
    CONSTRAINT "FK_Report_Parameter" FOREIGN KEY ("ParameterId") REFERENCES "Core"."Parameter" ("ParameterId"),
    CONSTRAINT "FK_Report_Station" FOREIGN KEY ("StationId") REFERENCES "Core"."Station" ("StationId"),
    CONSTRAINT "FK_Report_User" FOREIGN KEY ("RequestedByUserId") REFERENCES "Security"."User" ("UserId")
);

CREATE TABLE "Reporting"."ReportSchedule" (
    "ReportScheduleId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" uuid NOT NULL,
    "CreatedByUserId" uuid NOT NULL,
    "StationId" uuid,
    "ParameterId" integer,
    "Frequency" character varying(20) NOT NULL,
    "Format" character varying(20) NOT NULL,
    "RecipientJson" text NOT NULL,
    "NextRunAtUtc" timestamp(3) with time zone NOT NULL,
    "LastRunAtUtc" timestamp(3) with time zone,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_ReportSchedule" PRIMARY KEY ("ReportScheduleId"),
    CONSTRAINT "FK_ReportSchedule_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId"),
    CONSTRAINT "FK_ReportSchedule_Parameter" FOREIGN KEY ("ParameterId") REFERENCES "Core"."Parameter" ("ParameterId"),
    CONSTRAINT "FK_ReportSchedule_Station" FOREIGN KEY ("StationId") REFERENCES "Core"."Station" ("StationId"),
    CONSTRAINT "FK_ReportSchedule_User" FOREIGN KEY ("CreatedByUserId") REFERENCES "Security"."User" ("UserId")
);

CREATE TABLE "AI"."RiskScore" (
    "RiskScoreId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" uuid NOT NULL,
    "StationId" uuid,
    "RegionId" uuid,
    "Score" numeric(6,2) NOT NULL,
    "ForecastProximity" numeric(6,3),
    "UpstreamPropagation" numeric(6,3),
    "AnomalyPresence" numeric(6,3),
    "TrendSlope" numeric(18,8),
    "WeightsJson" text,
    "ComputedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT "PK_RiskScore" PRIMARY KEY ("RiskScoreId"),
    CONSTRAINT "FK_RiskScore_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId"),
    CONSTRAINT "FK_RiskScore_Region" FOREIGN KEY ("RegionId") REFERENCES "Core"."Region" ("RegionId"),
    CONSTRAINT "FK_RiskScore_Station" FOREIGN KEY ("StationId") REFERENCES "Core"."Station" ("StationId")
);

CREATE TABLE "Platform"."ShareSnapshot" (
    "ShareSnapshotId" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "OrganizationId" uuid NOT NULL,
    "CreatedByUserId" uuid NOT NULL,
    "StationId" uuid,
    "SnapshotJson" text NOT NULL,
    "TokenHash" character varying(128) NOT NULL,
    "ExpiresAtUtc" timestamp(3) with time zone NOT NULL,
    "RevokedAtUtc" timestamp(3) with time zone,
    "CreatedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT "PK_ShareSnapshot" PRIMARY KEY ("ShareSnapshotId"),
    CONSTRAINT "FK_ShareSnapshot_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId"),
    CONSTRAINT "FK_ShareSnapshot_Station" FOREIGN KEY ("StationId") REFERENCES "Core"."Station" ("StationId"),
    CONSTRAINT "FK_ShareSnapshot_User" FOREIGN KEY ("CreatedByUserId") REFERENCES "Security"."User" ("UserId")
);

CREATE TABLE "Operations"."StationCollaborationNote" (
    "NoteId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" uuid NOT NULL,
    "StationId" uuid NOT NULL,
    "AuthorUserId" uuid NOT NULL,
    "ParentNoteId" bigint,
    "NoteText" character varying(4000) NOT NULL,
    "IsResolved" boolean NOT NULL,
    "CreatedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    "UpdatedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT "PK_StationCollaborationNote" PRIMARY KEY ("NoteId"),
    CONSTRAINT "FK_Note_Author" FOREIGN KEY ("AuthorUserId") REFERENCES "Security"."User" ("UserId"),
    CONSTRAINT "FK_Note_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId"),
    CONSTRAINT "FK_Note_Parent" FOREIGN KEY ("ParentNoteId") REFERENCES "Operations"."StationCollaborationNote" ("NoteId"),
    CONSTRAINT "FK_Note_Station" FOREIGN KEY ("StationId") REFERENCES "Core"."Station" ("StationId")
);

CREATE TABLE "Core"."StationConnection" (
    "StationConnectionId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "StationId" uuid NOT NULL,
    "Protocol" character varying(30) NOT NULL,
    "DeviceIdentifier" character varying(150),
    "FirmwareVersion" character varying(80),
    "SignalStrength" numeric(10,3),
    "BatteryVoltage" numeric(10,4),
    "IsPrimary" boolean NOT NULL DEFAULT TRUE,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "LastConnectedAtUtc" timestamp(3) with time zone,
    CONSTRAINT "PK_StationConnection" PRIMARY KEY ("StationConnectionId"),
    CONSTRAINT "FK_StationConnection_Station" FOREIGN KEY ("StationId") REFERENCES "Core"."Station" ("StationId") ON DELETE CASCADE
);

CREATE TABLE "Core"."StationLink" (
    "StationLinkId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" uuid NOT NULL,
    "FromStationId" uuid NOT NULL,
    "ToStationId" uuid NOT NULL,
    "LinkType" character varying(30) NOT NULL DEFAULT 'DOWNSTREAM',
    "DistanceMeters" numeric(12,3),
    "FlowDirection" character varying(20) NOT NULL DEFAULT 'FORWARD',
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_StationLink" PRIMARY KEY ("StationLinkId"),
    CONSTRAINT "FK_StationLink_From" FOREIGN KEY ("FromStationId") REFERENCES "Core"."Station" ("StationId"),
    CONSTRAINT "FK_StationLink_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId") ON DELETE CASCADE,
    CONSTRAINT "FK_StationLink_To" FOREIGN KEY ("ToStationId") REFERENCES "Core"."Station" ("StationId")
);

CREATE TABLE "Core"."StationParameter" (
    "StationId" uuid NOT NULL,
    "ParameterId" integer NOT NULL,
    "SourceUnit" character varying(32) NOT NULL,
    "IsEnabled" boolean NOT NULL DEFAULT TRUE,
    "CalibrationOffset" numeric(18,6) NOT NULL,
    "CalibrationScale" numeric(18,6) NOT NULL DEFAULT 1.0,
    "InstalledAtUtc" timestamp(3) with time zone,
    "LastCalibrationAtUtc" timestamp(3) with time zone,
    CONSTRAINT "PK_StationParameter" PRIMARY KEY ("StationId", "ParameterId"),
    CONSTRAINT "FK_StationParameter_Parameter" FOREIGN KEY ("ParameterId") REFERENCES "Core"."Parameter" ("ParameterId"),
    CONSTRAINT "FK_StationParameter_Station" FOREIGN KEY ("StationId") REFERENCES "Core"."Station" ("StationId") ON DELETE CASCADE
);

CREATE TABLE "Operations"."AlarmLabel" (
    "AlarmLabelId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AlarmId" uuid NOT NULL,
    "Label" character varying(30) NOT NULL,
    "LabeledByUserId" uuid NOT NULL,
    "LabeledAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    "Notes" character varying(1000),
    CONSTRAINT "PK_AlarmLabel" PRIMARY KEY ("AlarmLabelId"),
    CONSTRAINT "FK_AlarmLabel_Alarm" FOREIGN KEY ("AlarmId") REFERENCES "Operations"."Alarm" ("AlarmId") ON DELETE CASCADE,
    CONSTRAINT "FK_AlarmLabel_User" FOREIGN KEY ("LabeledByUserId") REFERENCES "Security"."User" ("UserId")
);

CREATE TABLE "Operations"."Notification" (
    "NotificationId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "AlarmId" uuid,
    "Title" character varying(250) NOT NULL,
    "Body" character varying(2000) NOT NULL,
    "Severity" character varying(20) NOT NULL DEFAULT 'INFO',
    "Channel" character varying(20) NOT NULL DEFAULT 'IN_APP',
    "ReadAtUtc" timestamp(3) with time zone,
    "SentAtUtc" timestamp(3) with time zone,
    "CreatedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT "PK_Notification" PRIMARY KEY ("NotificationId"),
    CONSTRAINT "FK_Notification_Alarm" FOREIGN KEY ("AlarmId") REFERENCES "Operations"."Alarm" ("AlarmId"),
    CONSTRAINT "FK_Notification_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId"),
    CONSTRAINT "FK_Notification_User" FOREIGN KEY ("UserId") REFERENCES "Security"."User" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "AI"."MlTrainingRun" (
    "TrainingRunId" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "ModelId" uuid,
    "OrganizationId" uuid NOT NULL,
    "StartedAtUtc" timestamp(3) with time zone NOT NULL,
    "FinishedAtUtc" timestamp(3) with time zone,
    "DatasetStartUtc" timestamp(3) with time zone,
    "DatasetEndUtc" timestamp(3) with time zone,
    "FeatureSetVersion" character varying(50),
    "CleaningRulesetVersion" character varying(50),
    "TriggerSource" character varying(30) NOT NULL,
    "Status" character varying(20) NOT NULL DEFAULT 'RUNNING',
    "MetricsJson" text,
    "ErrorMessage" character varying(4000),
    "RowsRead" bigint NOT NULL,
    CONSTRAINT "PK_MlTrainingRun" PRIMARY KEY ("TrainingRunId"),
    CONSTRAINT "FK_TrainingRun_FeatureSet" FOREIGN KEY ("FeatureSetVersion") REFERENCES "Telemetry"."FeatureSet" ("FeatureSetVersion"),
    CONSTRAINT "FK_TrainingRun_Model" FOREIGN KEY ("ModelId") REFERENCES "AI"."MlModel" ("ModelId"),
    CONSTRAINT "FK_TrainingRun_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId")
);

CREATE TABLE "AI"."StationCluster" (
    "StationClusterId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" uuid NOT NULL,
    "StationId" uuid NOT NULL,
    "ClusterId" integer NOT NULL,
    "ClusterProfile" character varying(200),
    "FeatureVectorJson" text,
    "AssignedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    "ModelId" uuid,
    CONSTRAINT "PK_StationCluster" PRIMARY KEY ("StationClusterId"),
    CONSTRAINT "FK_StationCluster_Model" FOREIGN KEY ("ModelId") REFERENCES "AI"."MlModel" ("ModelId"),
    CONSTRAINT "FK_StationCluster_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId"),
    CONSTRAINT "FK_StationCluster_Station" FOREIGN KEY ("StationId") REFERENCES "Core"."Station" ("StationId")
);

CREATE TABLE "Telemetry"."FeatureStoreEntry" (
    "FeatureStoreEntryId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" uuid NOT NULL,
    "StationId" uuid NOT NULL,
    "ParameterId" integer NOT NULL,
    "TimestampUtc" timestamp(3) with time zone NOT NULL,
    "FeatureSetVersion" character varying(50) NOT NULL,
    "FeaturesJson" text NOT NULL,
    "SourceQualitySummary" character varying(20) NOT NULL DEFAULT 'VALID',
    "ComputedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT "PK_FeatureStoreEntry" PRIMARY KEY ("FeatureStoreEntryId"),
    CONSTRAINT "FK_FeatureStore_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId"),
    CONSTRAINT "FK_FeatureStore_Set" FOREIGN KEY ("FeatureSetVersion") REFERENCES "Telemetry"."FeatureSet" ("FeatureSetVersion"),
    CONSTRAINT "FK_FeatureStore_StationParameter" FOREIGN KEY ("StationId", "ParameterId") REFERENCES "Core"."StationParameter" ("StationId", "ParameterId")
);

CREATE TABLE "Telemetry"."MeasurementRaw" (
    "MeasurementRawId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" uuid NOT NULL,
    "StationId" uuid NOT NULL,
    "ParameterId" integer NOT NULL,
    "IngestionBatchId" uuid,
    "DeviceTimestampUtc" timestamp(3) with time zone NOT NULL,
    "IngestionTimestampUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    "RawValue" numeric(38,12),
    "RawUnit" character varying(32),
    "PayloadJson" text,
    "DeviceSequence" bigint,
    "DuplicateOfId" bigint,
    "IsDuplicate" boolean NOT NULL,
    "CreatedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT "PK_MeasurementRaw" PRIMARY KEY ("MeasurementRawId"),
    CONSTRAINT "FK_Raw_Batch" FOREIGN KEY ("IngestionBatchId") REFERENCES "Telemetry"."IngestionBatch" ("IngestionBatchId"),
    CONSTRAINT "FK_Raw_Duplicate" FOREIGN KEY ("DuplicateOfId") REFERENCES "Telemetry"."MeasurementRaw" ("MeasurementRawId"),
    CONSTRAINT "FK_Raw_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId"),
    CONSTRAINT "FK_Raw_StationParameter" FOREIGN KEY ("StationId", "ParameterId") REFERENCES "Core"."StationParameter" ("StationId", "ParameterId")
);

CREATE TABLE "Core"."Threshold" (
    "ThresholdId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" uuid NOT NULL,
    "StationId" uuid NOT NULL,
    "ParameterId" integer NOT NULL,
    "WarningLow" numeric(18,6),
    "WarningHigh" numeric(18,6),
    "CriticalLow" numeric(18,6),
    "CriticalHigh" numeric(18,6),
    "EffectiveFromUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    "EffectiveToUtc" timestamp(3) with time zone,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "UpdatedByUserId" uuid,
    CONSTRAINT "PK_Threshold" PRIMARY KEY ("ThresholdId"),
    CONSTRAINT "FK_Threshold_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId") ON DELETE CASCADE,
    CONSTRAINT "FK_Threshold_StationParameter" FOREIGN KEY ("StationId", "ParameterId") REFERENCES "Core"."StationParameter" ("StationId", "ParameterId"),
    CONSTRAINT "FK_Threshold_User" FOREIGN KEY ("UpdatedByUserId") REFERENCES "Security"."User" ("UserId")
);

CREATE TABLE "Telemetry"."MeasurementClean" (
    "MeasurementCleanId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" uuid NOT NULL,
    "StationId" uuid NOT NULL,
    "ParameterId" integer NOT NULL,
    "SourceRawId" bigint,
    "TimestampUtc" timestamp(3) with time zone NOT NULL,
    "Value" numeric(38,12),
    "CanonicalUnit" character varying(32) NOT NULL,
    "QualityFlag" character varying(20) NOT NULL DEFAULT 'VALID',
    "QuarantineReason" character varying(80),
    "CleaningRulesetVersion" character varying(50) NOT NULL,
    "IsInterpolated" boolean NOT NULL,
    "IsGapBoundary" boolean NOT NULL,
    "ProcessedAtUtc" timestamp(3) with time zone NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT "PK_MeasurementClean" PRIMARY KEY ("MeasurementCleanId"),
    CONSTRAINT "FK_Clean_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId"),
    CONSTRAINT "FK_Clean_Raw" FOREIGN KEY ("SourceRawId") REFERENCES "Telemetry"."MeasurementRaw" ("MeasurementRawId"),
    CONSTRAINT "FK_Clean_StationParameter" FOREIGN KEY ("StationId", "ParameterId") REFERENCES "Core"."StationParameter" ("StationId", "ParameterId")
);

CREATE TABLE "AI"."AnomalyEvent" (
    "AnomalyEventId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" uuid NOT NULL,
    "StationId" uuid NOT NULL,
    "ParameterId" integer,
    "MeasurementCleanId" bigint,
    "ReasonCode" character varying(30) NOT NULL,
    "Score" numeric(9,6) NOT NULL,
    "DetectedAtUtc" timestamp(3) with time zone NOT NULL,
    "WindowMinutes" integer,
    "DetailsJson" text,
    "IsReviewed" boolean NOT NULL,
    CONSTRAINT "PK_AnomalyEvent" PRIMARY KEY ("AnomalyEventId"),
    CONSTRAINT "FK_Anomaly_Measurement" FOREIGN KEY ("MeasurementCleanId") REFERENCES "Telemetry"."MeasurementClean" ("MeasurementCleanId"),
    CONSTRAINT "FK_Anomaly_Organization" FOREIGN KEY ("OrganizationId") REFERENCES "Platform"."Organization" ("OrganizationId"),
    CONSTRAINT "FK_Anomaly_Parameter" FOREIGN KEY ("ParameterId") REFERENCES "Core"."Parameter" ("ParameterId"),
    CONSTRAINT "FK_Anomaly_Station" FOREIGN KEY ("StationId") REFERENCES "Core"."Station" ("StationId")
);

CREATE INDEX "IX_Alarm_AcknowledgedByUserId" ON "Operations"."Alarm" ("AcknowledgedByUserId");

CREATE INDEX "IX_Alarm_AlarmTypeId" ON "Operations"."Alarm" ("AlarmTypeId");

CREATE INDEX "IX_Alarm_Open" ON "Operations"."Alarm" ("OrganizationId", "Status", "Severity", "RaisedAtUtc" DESC);

CREATE INDEX "IX_Alarm_ParameterId" ON "Operations"."Alarm" ("ParameterId");

CREATE INDEX "IX_Alarm_ResolvedByUserId" ON "Operations"."Alarm" ("ResolvedByUserId");

CREATE INDEX "IX_Alarm_Station_Date" ON "Operations"."Alarm" ("StationId", "RaisedAtUtc" DESC);

CREATE INDEX "IX_AlarmLabel_AlarmId" ON "Operations"."AlarmLabel" ("AlarmId");

CREATE INDEX "IX_AlarmLabel_LabeledByUserId" ON "Operations"."AlarmLabel" ("LabeledByUserId");

CREATE UNIQUE INDEX "UQ_AlarmType_Code" ON "Operations"."AlarmType" ("Code");

CREATE INDEX "IX_Anomaly_Station_Date" ON "AI"."AnomalyEvent" ("StationId", "DetectedAtUtc" DESC);

CREATE INDEX "IX_AnomalyEvent_MeasurementCleanId" ON "AI"."AnomalyEvent" ("MeasurementCleanId");

CREATE INDEX "IX_AnomalyEvent_OrganizationId" ON "AI"."AnomalyEvent" ("OrganizationId");

CREATE INDEX "IX_AnomalyEvent_ParameterId" ON "AI"."AnomalyEvent" ("ParameterId");

CREATE INDEX "IX_AuditLog_ActorUserId" ON "Security"."AuditLog" ("ActorUserId");

CREATE INDEX "IX_AuditLog_OrganizationId" ON "Security"."AuditLog" ("OrganizationId");

CREATE INDEX "IX_ChartAnnotation_OrganizationId" ON "Operations"."ChartAnnotation" ("OrganizationId");

CREATE INDEX "IX_ChartAnnotation_ParameterId" ON "Operations"."ChartAnnotation" ("ParameterId");

CREATE INDEX "IX_ChartAnnotation_StationId" ON "Operations"."ChartAnnotation" ("StationId");

CREATE INDEX "IX_ChartAnnotation_UserId" ON "Operations"."ChartAnnotation" ("UserId");

CREATE UNIQUE INDEX "UQ_DashboardLayout" ON "Platform"."DashboardLayout" ("UserId", "LayoutName");

CREATE INDEX "IX_DataQualityLog_OrganizationId" ON "Telemetry"."DataQualityLog" ("OrganizationId");

CREATE INDEX "IX_DataQualityLog_StationId" ON "Telemetry"."DataQualityLog" ("StationId");

CREATE INDEX "IX_FeatureStoreEntry_FeatureSetVersion" ON "Telemetry"."FeatureStoreEntry" ("FeatureSetVersion");

CREATE INDEX "IX_FeatureStoreEntry_OrganizationId" ON "Telemetry"."FeatureStoreEntry" ("OrganizationId");

CREATE UNIQUE INDEX "UX_FeatureStore_Key" ON "Telemetry"."FeatureStoreEntry" ("StationId", "ParameterId", "TimestampUtc", "FeatureSetVersion");

CREATE INDEX "IX_FocusStationScore_OrganizationId" ON "AI"."FocusStationScore" ("OrganizationId");

CREATE INDEX "IX_FocusStationScore_StationId" ON "AI"."FocusStationScore" ("StationId");

CREATE INDEX "IX_FocusStationScore_UserId" ON "AI"."FocusStationScore" ("UserId");

CREATE INDEX "IX_IngestionBatch_OrganizationId" ON "Telemetry"."IngestionBatch" ("OrganizationId");

CREATE INDEX "IX_Clean_Chart" ON "Telemetry"."MeasurementClean" ("StationId", "TimestampUtc");

CREATE INDEX "IX_Clean_Time" ON "Telemetry"."MeasurementClean" ("OrganizationId", "TimestampUtc", "QualityFlag");

CREATE INDEX "IX_MeasurementClean_SourceRawId" ON "Telemetry"."MeasurementClean" ("SourceRawId");

CREATE UNIQUE INDEX "UX_Clean_Key" ON "Telemetry"."MeasurementClean" ("StationId", "ParameterId", "TimestampUtc");

CREATE INDEX "IX_MeasurementRaw_DuplicateOfId" ON "Telemetry"."MeasurementRaw" ("DuplicateOfId");

CREATE INDEX "IX_MeasurementRaw_IngestionBatchId" ON "Telemetry"."MeasurementRaw" ("IngestionBatchId");

CREATE INDEX "IX_MeasurementRaw_OrganizationId" ON "Telemetry"."MeasurementRaw" ("OrganizationId");

CREATE INDEX "IX_Raw_Station_Time" ON "Telemetry"."MeasurementRaw" ("StationId", "ParameterId", "DeviceTimestampUtc");

CREATE INDEX "IX_MlModel_FeatureSetVersion" ON "AI"."MlModel" ("FeatureSetVersion");

CREATE INDEX "IX_MlModel_ParameterId" ON "AI"."MlModel" ("ParameterId");

CREATE INDEX "IX_MlModel_StationId" ON "AI"."MlModel" ("StationId");

CREATE UNIQUE INDEX "UX_MlModel_Version" ON "AI"."MlModel" ("OrganizationId", "ModelType", "StationId", "ParameterId", "Version");

CREATE INDEX "IX_MlTrainingRun_FeatureSetVersion" ON "AI"."MlTrainingRun" ("FeatureSetVersion");

CREATE INDEX "IX_MlTrainingRun_ModelId" ON "AI"."MlTrainingRun" ("ModelId");

CREATE INDEX "IX_MlTrainingRun_OrganizationId" ON "AI"."MlTrainingRun" ("OrganizationId");

CREATE INDEX "IX_Notification_AlarmId" ON "Operations"."Notification" ("AlarmId");

CREATE INDEX "IX_Notification_OrganizationId" ON "Operations"."Notification" ("OrganizationId");

CREATE INDEX "IX_Notification_Unread" ON "Operations"."Notification" ("UserId", "CreatedAtUtc" DESC) WHERE "ReadAtUtc" IS NULL;

CREATE UNIQUE INDEX "UQ_Organization_Name" ON "Platform"."Organization" ("Name");

CREATE UNIQUE INDEX "UQ_Organization_Slug" ON "Platform"."Organization" ("Slug");

CREATE UNIQUE INDEX "UQ_Parameter_Code" ON "Core"."Parameter" ("Code");

CREATE UNIQUE INDEX "UQ_Permission_Code" ON "Security"."Permission" ("Code");

CREATE UNIQUE INDEX "UQ_Region_Code" ON "Core"."Region" ("OrganizationId", "Code");

CREATE UNIQUE INDEX "UQ_Region_Name" ON "Core"."Region" ("OrganizationId", "Name");

CREATE INDEX "IX_Report_Date" ON "Reporting"."Report" ("OrganizationId", "CreatedAtUtc" DESC);

CREATE INDEX "IX_Report_ParameterId" ON "Reporting"."Report" ("ParameterId");

CREATE INDEX "IX_Report_RequestedByUserId" ON "Reporting"."Report" ("RequestedByUserId");

CREATE INDEX "IX_Report_StationId" ON "Reporting"."Report" ("StationId");

CREATE INDEX "IX_ReportSchedule_CreatedByUserId" ON "Reporting"."ReportSchedule" ("CreatedByUserId");

CREATE INDEX "IX_ReportSchedule_OrganizationId" ON "Reporting"."ReportSchedule" ("OrganizationId");

CREATE INDEX "IX_ReportSchedule_ParameterId" ON "Reporting"."ReportSchedule" ("ParameterId");

CREATE INDEX "IX_ReportSchedule_StationId" ON "Reporting"."ReportSchedule" ("StationId");

CREATE INDEX "IX_RiskScore_OrganizationId" ON "AI"."RiskScore" ("OrganizationId");

CREATE INDEX "IX_RiskScore_RegionId" ON "AI"."RiskScore" ("RegionId");

CREATE INDEX "IX_RiskScore_StationId" ON "AI"."RiskScore" ("StationId");

CREATE UNIQUE INDEX "UQ_Role_Code" ON "Security"."Role" ("Code");

CREATE INDEX "IX_RolePermission_PermissionId" ON "Security"."RolePermission" ("PermissionId");

CREATE INDEX "IX_Session_UserId" ON "Security"."Session" ("UserId");

CREATE UNIQUE INDEX "UX_Session_Token" ON "Security"."Session" ("RefreshTokenHash");

CREATE INDEX "IX_ShareSnapshot_CreatedByUserId" ON "Platform"."ShareSnapshot" ("CreatedByUserId");

CREATE INDEX "IX_ShareSnapshot_OrganizationId" ON "Platform"."ShareSnapshot" ("OrganizationId");

CREATE INDEX "IX_ShareSnapshot_StationId" ON "Platform"."ShareSnapshot" ("StationId");

CREATE UNIQUE INDEX "UQ_ShareSnapshot_Token" ON "Platform"."ShareSnapshot" ("TokenHash");

CREATE INDEX "IX_Station_RegionId" ON "Core"."Station" ("RegionId");

CREATE INDEX "IX_Station_Status" ON "Core"."Station" ("OrganizationId", "Status", "Name");

CREATE UNIQUE INDEX "UQ_Station_Code" ON "Core"."Station" ("OrganizationId", "StationCode");

CREATE INDEX "IX_StationCluster_ModelId" ON "AI"."StationCluster" ("ModelId");

CREATE INDEX "IX_StationCluster_OrganizationId" ON "AI"."StationCluster" ("OrganizationId");

CREATE INDEX "IX_StationCluster_StationId" ON "AI"."StationCluster" ("StationId");

CREATE INDEX "IX_StationCollaborationNote_AuthorUserId" ON "Operations"."StationCollaborationNote" ("AuthorUserId");

CREATE INDEX "IX_StationCollaborationNote_OrganizationId" ON "Operations"."StationCollaborationNote" ("OrganizationId");

CREATE INDEX "IX_StationCollaborationNote_ParentNoteId" ON "Operations"."StationCollaborationNote" ("ParentNoteId");

CREATE INDEX "IX_StationCollaborationNote_StationId" ON "Operations"."StationCollaborationNote" ("StationId");

CREATE INDEX "IX_StationConnection_StationId" ON "Core"."StationConnection" ("StationId");

CREATE UNIQUE INDEX "UX_StationConnection_Device" ON "Core"."StationConnection" ("DeviceIdentifier") WHERE "DeviceIdentifier" IS NOT NULL;

CREATE INDEX "IX_StationLink_OrganizationId" ON "Core"."StationLink" ("OrganizationId");

CREATE INDEX "IX_StationLink_ToStationId" ON "Core"."StationLink" ("ToStationId");

CREATE UNIQUE INDEX "UQ_StationLink" ON "Core"."StationLink" ("FromStationId", "ToStationId");

CREATE INDEX "IX_StationParameter_ParameterId" ON "Core"."StationParameter" ("ParameterId");

CREATE UNIQUE INDEX "UQ_SystemSetting" ON "Platform"."SystemSetting" ("OrganizationId", "SettingKey");

CREATE INDEX "IX_Threshold_Current" ON "Core"."Threshold" ("StationId", "ParameterId", "EffectiveFromUtc" DESC) WHERE "IsActive" = TRUE;

CREATE INDEX "IX_Threshold_OrganizationId" ON "Core"."Threshold" ("OrganizationId");

CREATE INDEX "IX_Threshold_UpdatedByUserId" ON "Core"."Threshold" ("UpdatedByUserId");

CREATE INDEX "IX_User_Active" ON "Security"."User" ("OrganizationId", "IsActive");

CREATE UNIQUE INDEX "UX_User_Email" ON "Security"."User" ("OrganizationId", "Email");

CREATE INDEX "IX_UserRole_AssignedByUserId" ON "Security"."UserRole" ("AssignedByUserId");

CREATE INDEX "IX_UserRole_RoleId" ON "Security"."UserRole" ("RoleId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260821140720_InitialPostgreSqlSchema', '10.0.11');

COMMIT;
START TRANSACTION;
CREATE OR REPLACE VIEW "Reporting"."vw_OrganizationKpis" AS
SELECT o."OrganizationId", o."Name" AS "OrganizationName",
       COUNT(DISTINCT s."StationId")::integer AS "TotalStations",
       COUNT(DISTINCT CASE WHEN s."Status" = 'ONLINE' THEN s."StationId" END)::integer AS "OnlineStations",
       COUNT(DISTINCT CASE WHEN s."Status" = 'OFFLINE' THEN s."StationId" END)::integer AS "OfflineStations",
       COUNT(DISTINCT CASE WHEN a."Status" IN ('ACTIVE','ACKNOWLEDGED') THEN a."AlarmId" END)::integer AS "OpenAlarms",
       COUNT(DISTINCT CASE WHEN a."Status" IN ('ACTIVE','ACKNOWLEDGED') AND a."Severity" = 'CRITICAL' THEN a."AlarmId" END)::integer AS "CriticalAlarms",
       COUNT(DISTINCT CASE WHEN a."Status" IN ('ACTIVE','ACKNOWLEDGED') AND a."Severity" = 'WARNING' THEN a."AlarmId" END)::integer AS "WarningAlarms"
FROM "Platform"."Organization" o
LEFT JOIN "Core"."Station" s ON s."OrganizationId" = o."OrganizationId" AND s."IsActive" = TRUE
LEFT JOIN "Operations"."Alarm" a ON a."OrganizationId" = o."OrganizationId"
GROUP BY o."OrganizationId", o."Name";

CREATE OR REPLACE VIEW "Reporting"."vw_CurrentTelemetry" AS
WITH latest AS (
    SELECT mc.*, ROW_NUMBER() OVER (PARTITION BY mc."StationId", mc."ParameterId" ORDER BY mc."TimestampUtc" DESC, mc."MeasurementCleanId" DESC) AS rn
    FROM "Telemetry"."MeasurementClean" mc WHERE mc."QualityFlag" <> 'QUARANTINED'
)
SELECT s."OrganizationId", s."StationId", s."StationCode", s."Name" AS "StationName",
       p."ParameterId", p."Code" AS "ParameterCode", p."Name" AS "ParameterName",
       p."CanonicalUnit", latest."TimestampUtc", latest."Value", latest."QualityFlag", latest."IsInterpolated"
FROM latest JOIN "Core"."Station" s ON s."StationId" = latest."StationId"
JOIN "Core"."Parameter" p ON p."ParameterId" = latest."ParameterId" WHERE latest.rn = 1;

CREATE OR REPLACE VIEW "Reporting"."vw_DataQualityLatest" AS
WITH latest AS (
    SELECT d.*, ROW_NUMBER() OVER (PARTITION BY d."StationId" ORDER BY d."WindowEndUtc" DESC, d."DataQualityLogId" DESC) AS rn
    FROM "Telemetry"."DataQualityLog" d
)
SELECT latest."OrganizationId", latest."StationId", s."StationCode", s."Name" AS "StationName",
       latest."WindowStartUtc", latest."WindowEndUtc", latest."TotalCount", latest."ValidCount",
       latest."InterpolatedCount", latest."QuarantinedCount", latest."DuplicateCount",
       latest."ValidPct", latest."InterpolatedPct", latest."QuarantinedPct",
       latest."SchemaDriftEvents", latest."RulesetVersion"
FROM latest JOIN "Core"."Station" s ON s."StationId" = latest."StationId" WHERE latest.rn = 1;

CREATE OR REPLACE VIEW "Reporting"."vw_ActiveAlarms" AS
SELECT a."OrganizationId", a."AlarmId", a."StationId", s."StationCode", s."Name" AS "StationName",
       r."Name" AS "RegionName", at."Code" AS "AlarmType", at."Name" AS "AlarmTypeName",
       a."ParameterId", p."Code" AS "ParameterCode", a."Severity", a."Status", a."Message",
       a."ValueAtRaise", a."ThresholdValue", a."RaisedAtUtc", a."AcknowledgedAtUtc",
       u."DisplayName" AS "AcknowledgedBy",
       EXTRACT(EPOCH FROM (COALESCE(a."AcknowledgedAtUtc", timezone('utc', now())) - a."RaisedAtUtc"))::integer / 60 AS "MinutesToAcknowledge"
FROM "Operations"."Alarm" a JOIN "Core"."Station" s ON s."StationId" = a."StationId"
LEFT JOIN "Core"."Region" r ON r."RegionId" = s."RegionId"
JOIN "Operations"."AlarmType" at ON at."AlarmTypeId" = a."AlarmTypeId"
LEFT JOIN "Core"."Parameter" p ON p."ParameterId" = a."ParameterId"
LEFT JOIN "Security"."User" u ON u."UserId" = a."AcknowledgedByUserId"
WHERE a."Status" IN ('ACTIVE','ACKNOWLEDGED');

CREATE OR REPLACE VIEW "Reporting"."vw_StationDirectory" AS
SELECT s."OrganizationId", o."Name" AS "OrganizationName", r."RegionId", r."Name" AS "RegionName",
       s."StationId", s."StationCode", s."Name" AS "StationName", s."Status", s."Latitude", s."Longitude",
       s."LastSeenAtUtc", COUNT(DISTINCT sp."ParameterId")::integer AS "EnabledParameterCount",
       COUNT(DISTINCT CASE WHEN a."Status" IN ('ACTIVE','ACKNOWLEDGED') THEN a."AlarmId" END)::integer AS "OpenAlarmCount",
       COUNT(DISTINCT CASE WHEN a."Status" IN ('ACTIVE','ACKNOWLEDGED') AND a."Severity" = 'CRITICAL' THEN a."AlarmId" END)::integer AS "CriticalAlarmCount"
FROM "Core"."Station" s JOIN "Platform"."Organization" o ON o."OrganizationId" = s."OrganizationId"
LEFT JOIN "Core"."Region" r ON r."RegionId" = s."RegionId"
LEFT JOIN "Core"."StationParameter" sp ON sp."StationId" = s."StationId" AND sp."IsEnabled" = TRUE
LEFT JOIN "Operations"."Alarm" a ON a."StationId" = s."StationId" WHERE s."IsActive" = TRUE
GROUP BY s."OrganizationId", o."Name", r."RegionId", r."Name", s."StationId", s."StationCode",
         s."Name", s."Status", s."Latitude", s."Longitude", s."LastSeenAtUtc";

CREATE OR REPLACE VIEW "Reporting"."vw_ModelHealth" AS
SELECT m."OrganizationId", m."ModelId", m."ModelType", m."StationId", s."StationCode",
       m."ParameterId", p."Code" AS "ParameterCode", m."Version", m."Status", m."TrainedAtUtc",
       m."PromotedAtUtc", m."FeatureSetVersion", m."CleaningRulesetVersion", m."MetricsJson",
       COUNT(tr."TrainingRunId")::integer AS "TrainingRunCount", MAX(tr."FinishedAtUtc") AS "LastTrainingFinishedAtUtc"
FROM "AI"."MlModel" m LEFT JOIN "Core"."Station" s ON s."StationId" = m."StationId"
LEFT JOIN "Core"."Parameter" p ON p."ParameterId" = m."ParameterId"
LEFT JOIN "AI"."MlTrainingRun" tr ON tr."ModelId" = m."ModelId"
GROUP BY m."OrganizationId", m."ModelId", m."ModelType", m."StationId", s."StationCode", m."ParameterId",
         p."Code", m."Version", m."Status", m."TrainedAtUtc", m."PromotedAtUtc", m."FeatureSetVersion",
         m."CleaningRulesetVersion", m."MetricsJson";

CREATE OR REPLACE VIEW "Reporting"."vw_StationRiskLatest" AS
WITH latest AS (
    SELECT r.*, ROW_NUMBER() OVER (PARTITION BY r."OrganizationId", r."StationId", r."RegionId" ORDER BY r."ComputedAtUtc" DESC, r."RiskScoreId" DESC) AS rn
    FROM "AI"."RiskScore" r
)
SELECT latest.*, s."StationCode", s."Name" AS "StationName", rg."Name" AS "RegionName"
FROM latest LEFT JOIN "Core"."Station" s ON s."StationId" = latest."StationId"
LEFT JOIN "Core"."Region" rg ON rg."RegionId" = latest."RegionId" WHERE latest.rn = 1;

CREATE OR REPLACE FUNCTION "Reporting"."ufn_StationMeasurements"(
    p_station_id uuid, p_parameter_id integer, p_from_utc timestamptz, p_to_utc timestamptz,
    p_include_interpolated boolean DEFAULT TRUE
) RETURNS TABLE(
    "MeasurementCleanId" bigint, "StationId" uuid, "StationCode" text, "StationName" text,
    "ParameterId" integer, "ParameterCode" text, "ParameterName" text, "TimestampUtc" timestamptz,
    "Value" numeric, "CanonicalUnit" text, "QualityFlag" text, "IsInterpolated" boolean
) LANGUAGE sql STABLE AS $$
    SELECT mc."MeasurementCleanId", mc."StationId", s."StationCode", s."Name",
           mc."ParameterId", p."Code", p."Name", mc."TimestampUtc", mc."Value",
           mc."CanonicalUnit", mc."QualityFlag", mc."IsInterpolated"
    FROM "Telemetry"."MeasurementClean" mc JOIN "Core"."Station" s ON s."StationId" = mc."StationId"
    JOIN "Core"."Parameter" p ON p."ParameterId" = mc."ParameterId"
    WHERE mc."StationId" = p_station_id AND mc."ParameterId" = p_parameter_id
      AND mc."TimestampUtc" >= p_from_utc AND mc."TimestampUtc" < p_to_utc
      AND mc."QualityFlag" <> 'QUARANTINED' AND (p_include_interpolated OR NOT mc."IsInterpolated")
$$;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260821140834_AddPostgreSqlReportingObjects', '10.0.11');

COMMIT;

