// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class Alarm
{
    public Guid AlarmId { get; set; }

    public Guid OrganizationId { get; set; }

    public Guid StationId { get; set; }

    public int? ParameterId { get; set; }

    public int AlarmTypeId { get; set; }

    public string Severity { get; set; }

    public string Status { get; set; }

    public string Message { get; set; }

    public decimal? ValueAtRaise { get; set; }

    public decimal? ThresholdValue { get; set; }

    public DateTime RaisedAtUtc { get; set; }

    public DateTime? AcknowledgedAtUtc { get; set; }

    public Guid? AcknowledgedByUserId { get; set; }

    public DateTime? ResolvedAtUtc { get; set; }

    public Guid? ResolvedByUserId { get; set; }

    public string ResolutionNote { get; set; }

    public Guid? CorrelationClusterId { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual User AcknowledgedByUser { get; set; }

    public virtual ICollection<AlarmLabel> AlarmLabels { get; set; } = new List<AlarmLabel>();

    public virtual AlarmType AlarmType { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual Organization Organization { get; set; }

    public virtual Parameter Parameter { get; set; }

    public virtual User ResolvedByUser { get; set; }

    public virtual Station Station { get; set; }
}