// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class AlarmLabel
{
    public long AlarmLabelId { get; set; }

    public Guid AlarmId { get; set; }

    public string Label { get; set; }

    public Guid LabeledByUserId { get; set; }

    public DateTime LabeledAtUtc { get; set; }

    public string Notes { get; set; }

    public virtual Alarm Alarm { get; set; }

    public virtual User LabeledByUser { get; set; }
}