// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class ChartAnnotation
{
    public long ChartAnnotationId { get; set; }

    public Guid OrganizationId { get; set; }

    public Guid StationId { get; set; }

    public int? ParameterId { get; set; }

    public Guid UserId { get; set; }

    public DateTime TimestampUtc { get; set; }

    public string Text { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual Parameter Parameter { get; set; }

    public virtual Station Station { get; set; }

    public virtual User User { get; set; }
}