// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class NotificationPreference
{
    public Guid UserId { get; set; }

    public string Severity { get; set; }

    public bool InAppEnabled { get; set; }

    public bool EmailEnabled { get; set; }

    public bool PushEnabled { get; set; }

    public bool DesktopEnabled { get; set; }

    public bool DailyDigestEnabled { get; set; }

    public virtual User User { get; set; }
}