// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class Notification
{
    public long NotificationId { get; set; }

    public Guid OrganizationId { get; set; }

    public Guid UserId { get; set; }

    public Guid? AlarmId { get; set; }

    public string Title { get; set; }

    public string Body { get; set; }

    public string Severity { get; set; }

    public string Channel { get; set; }

    public DateTime? ReadAtUtc { get; set; }

    public DateTime? SentAtUtc { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual Alarm Alarm { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual User User { get; set; }
}