// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class StationCollaborationNote
{
    public long NoteId { get; set; }

    public Guid OrganizationId { get; set; }

    public Guid StationId { get; set; }

    public Guid AuthorUserId { get; set; }

    public long? ParentNoteId { get; set; }

    public string NoteText { get; set; }

    public bool IsResolved { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    public virtual User AuthorUser { get; set; }

    public virtual ICollection<StationCollaborationNote> InverseParentNote { get; set; } = new List<StationCollaborationNote>();

    public virtual Organization Organization { get; set; }

    public virtual StationCollaborationNote ParentNote { get; set; }

    public virtual Station Station { get; set; }
}