// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WaterOperations.Domain.Entities
{
    public partial class ufn_StationMeasurementsResult
    {
        public long MeasurementCleanId { get; set; }
        public Guid StationId { get; set; }
        [StringLength(80)]
        public string StationCode { get; set; }
        [StringLength(200)]
        public string StationName { get; set; }
        public int ParameterId { get; set; }
        [StringLength(50)]
        public string ParameterCode { get; set; }
        [StringLength(150)]
        public string ParameterName { get; set; }
        public DateTime TimestampUtc { get; set; }
        [Column("Value", TypeName = "decimal(38,12)")]
        public decimal? Value { get; set; }
        [StringLength(32)]
        public string CanonicalUnit { get; set; }
        [StringLength(20)]
        public string QualityFlag { get; set; }
        public bool IsInterpolated { get; set; }
        [Column("WarningLow", TypeName = "decimal(18,6)")]
        public decimal? WarningLow { get; set; }
        [Column("WarningHigh", TypeName = "decimal(18,6)")]
        public decimal? WarningHigh { get; set; }
        [Column("CriticalLow", TypeName = "decimal(18,6)")]
        public decimal? CriticalLow { get; set; }
        [Column("CriticalHigh", TypeName = "decimal(18,6)")]
        public decimal? CriticalHigh { get; set; }
    }
}
