using WaterOperations.Application.Common.Pagination;

namespace WaterOperations.Application.Features.ProductCapabilities.DTOs;

public sealed record AnomalyDto(long Id, Guid StationId, string ReasonCode, decimal Score, DateTime DetectedAtUtc, bool IsReviewed);
public sealed record ModelDto(Guid ModelId, string ModelType, string Version, string Status, DateTime? PromotedAtUtc);
public sealed record ReportDto(Guid ReportId, Guid? StationId, string Format, string Status, DateTime PeriodStartUtc, DateTime PeriodEndUtc, DateTime CreatedAtUtc, string? FilePath);
public sealed record ReportDownloadDto(Stream Content, string ContentType, string FileName);
public sealed record NotificationDto(long Id, string Title, string Body, string Severity, string Channel, bool IsRead, DateTime CreatedAtUtc);
public sealed record AuditEntryDto(long Id, string ActionCode, string? EntityType, string? EntityId, bool Success, DateTime OccurredAtUtc, Guid? ActorUserId, string? RequestId = null, string? BeforeJson = null, string? AfterJson = null);
public sealed record UserAdminDto(Guid UserId, string Email, string DisplayName, string ClientType, bool IsActive, DateTime CreatedAtUtc);
public sealed record RegionAdminDto(Guid RegionId, Guid OrganizationId, string Code, string Name, string? Description, bool IsActive, DateTime CreatedAtUtc);
public sealed record UserRoleDto(Guid UserId, int RoleId, string Code, string DisplayName, DateTime AssignedAtUtc);
public sealed record CreateRegionRequest(string Code, string Name, string? Description, string? BoundaryJson);
public sealed record UpdateRegionRequest(string Code, string Name, string? Description, string? BoundaryJson, bool IsActive);
public sealed record AssignUserRoleRequest(int RoleId);
public sealed record OrganizationDto(Guid OrganizationId, string Name, string Slug, string? LogoUrl, string DefaultLocale, string DefaultTimeZone, bool IsActive);
public sealed record DashboardLayoutDto(long Id, string LayoutName, string WidgetsJson, bool IsDefault, DateTime UpdatedAtUtc);
public sealed record SearchResultDto(string Type, string Id, string Title, string? Subtitle);
public sealed record CollaborationNoteDto(long NoteId, Guid StationId, Guid AuthorUserId, string NoteText, bool IsResolved, DateTime CreatedAtUtc, DateTime UpdatedAtUtc);
public sealed record SharedSnapshotDto(Guid ShareSnapshotId, Guid? StationId, DateTime ExpiresAtUtc, DateTime CreatedAtUtc, string? Token = null);
public sealed record SharedSnapshotContentDto(Guid ShareSnapshotId, Guid? StationId, string SnapshotJson, DateTime ExpiresAtUtc, DateTime CreatedAtUtc);
public sealed record AddCollaborationNoteRequest(string NoteText, long? ParentNoteId = null);
public sealed record ReportScheduleDto(long Id, string Frequency, string Format, string RecipientJson, DateTime NextRunAtUtc, DateTime? LastRunAtUtc, bool IsActive);
public sealed record CreateReportRequest(Guid? StationId, int? ParameterId, DateTime PeriodStartUtc, DateTime PeriodEndUtc, string Format);
public sealed record ReportFilter(Guid? StationId = null, int? ParameterId = null, DateTime? FromUtc = null, DateTime? ToUtc = null, string? Status = null);
public sealed record AuditFilter(DateTime? FromUtc = null, DateTime? ToUtc = null, Guid? ActorUserId = null, string? ActionCode = null, string? EntityType = null, string? EntityId = null);
public sealed record SetUserActiveRequest(bool IsActive);
public sealed record UserPreferencesDto(string Theme, string Locale, string TimeZone, byte DecimalPrecision);
public sealed record NotificationPreferenceDto(string Severity, bool InAppEnabled, bool EmailEnabled, bool PushEnabled, bool DesktopEnabled, bool DailyDigestEnabled);
public sealed record ModelMutationResult(bool Succeeded, string? ErrorCode);
public sealed record AiResourceRequest(Guid ResourceId);
public sealed record ProductPage<T>(PagedResult<T> Result);
