// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using WaterOperations.Application.Common.Repositories;
using WaterOperations.Domain.Entities;

namespace WaterOperations.Infrastructure.Persistence;

public partial class WaterOperationsDbContext : DbContext, IUnitOfWork
{
    public WaterOperationsDbContext(DbContextOptions<WaterOperationsDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Alarm> Alarms { get; set; }

    public virtual DbSet<AlarmLabel> AlarmLabels { get; set; }

    public virtual DbSet<AlarmType> AlarmTypes { get; set; }

    public virtual DbSet<AnomalyEvent> AnomalyEvents { get; set; }

    public virtual DbSet<AuditLog> AuditLogs { get; set; }

    public virtual DbSet<ChartAnnotation> ChartAnnotations { get; set; }

    public virtual DbSet<DashboardLayout> DashboardLayouts { get; set; }

    public virtual DbSet<DataQualityLog> DataQualityLogs { get; set; }

    public virtual DbSet<FeatureSet> FeatureSets { get; set; }

    public virtual DbSet<FeatureStoreEntry> FeatureStoreEntries { get; set; }

    public virtual DbSet<FocusStationScore> FocusStationScores { get; set; }

    public virtual DbSet<IngestionBatch> IngestionBatches { get; set; }

    public virtual DbSet<MeasurementClean> MeasurementCleans { get; set; }

    // Compatibility alias for the original viewer foundation tests/API terminology.
    public DbSet<MeasurementClean> Measurements => MeasurementCleans;

    public virtual DbSet<MeasurementRaw> MeasurementRaws { get; set; }

    public virtual DbSet<MfaRecoveryCode> MfaRecoveryCodes { get; set; }

    public virtual DbSet<MlModel> MlModels { get; set; }

    public virtual DbSet<MlTrainingRun> MlTrainingRuns { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<NotificationPreference> NotificationPreferences { get; set; }

    public virtual DbSet<OutboxMessage> OutboxMessages { get; set; }

    public virtual DbSet<Organization> Organizations { get; set; }

    public virtual DbSet<Parameter> Parameters { get; set; }

    public virtual DbSet<Permission> Permissions { get; set; }

    public virtual DbSet<Region> Regions { get; set; }

    public virtual DbSet<Report> Reports { get; set; }

    public virtual DbSet<ReportSchedule> ReportSchedules { get; set; }

    public virtual DbSet<RiskScore> RiskScores { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Session> Sessions { get; set; }

    public virtual DbSet<ShareSnapshot> ShareSnapshots { get; set; }

    public virtual DbSet<Station> Stations { get; set; }

    public virtual DbSet<StationCluster> StationClusters { get; set; }

    public virtual DbSet<StationCollaborationNote> StationCollaborationNotes { get; set; }

    public virtual DbSet<StationConnection> StationConnections { get; set; }

    public virtual DbSet<StationLink> StationLinks { get; set; }

    public virtual DbSet<StationParameter> StationParameters { get; set; }

    public virtual DbSet<SystemSetting> SystemSettings { get; set; }

    public virtual DbSet<Threshold> Thresholds { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<VwActiveAlarm> VwActiveAlarms { get; set; }

    public virtual DbSet<VwCurrentTelemetry> VwCurrentTelemetries { get; set; }

    public virtual DbSet<VwDataQualityLatest> VwDataQualityLatests { get; set; }

    public virtual DbSet<VwModelHealth> VwModelHealths { get; set; }

    public virtual DbSet<VwOrganizationKpi> VwOrganizationKpis { get; set; }

    public virtual DbSet<VwStationDirectory> VwStationDirectories { get; set; }

    public virtual DbSet<VwStationRiskLatest> VwStationRiskLatests { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Alarm>(entity =>
        {
            entity.HasKey(e => e.AlarmId);

            entity.ToTable("Alarm", "Operations");

            entity.HasIndex(e => new { e.OrganizationId, e.Status, e.Severity, e.RaisedAtUtc }, "IX_Alarm_Open").IsDescending(false, false, false, true);

            entity.HasIndex(e => new { e.StationId, e.RaisedAtUtc }, "IX_Alarm_Station_Date").IsDescending(false, true);

            entity.Property(e => e.AlarmId).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.AcknowledgedAtUtc).HasPrecision(3);
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.Message)
                .IsRequired()
                .HasMaxLength(1000);
            entity.Property(e => e.RaisedAtUtc).HasPrecision(3);
            entity.Property(e => e.ResolutionNote).HasMaxLength(2000);
            entity.Property(e => e.ResolvedAtUtc).HasPrecision(3);
            entity.Property(e => e.Severity)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("ACTIVE");
            entity.Property(e => e.ThresholdValue).HasColumnType("decimal(38, 12)");
            entity.Property(e => e.ValueAtRaise).HasColumnType("decimal(38, 12)");

            entity.HasOne(d => d.AcknowledgedByUser).WithMany(p => p.AlarmAcknowledgedByUsers)
                .HasForeignKey(d => d.AcknowledgedByUserId)
                .HasConstraintName("FK_Alarm_AckUser");

            entity.HasOne(d => d.AlarmType).WithMany(p => p.Alarms)
                .HasForeignKey(d => d.AlarmTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Alarm_Type");

            entity.HasOne(d => d.Organization).WithMany(p => p.Alarms)
                .HasForeignKey(d => d.OrganizationId)
                .HasConstraintName("FK_Alarm_Organization");

            entity.HasOne(d => d.Parameter).WithMany(p => p.Alarms)
                .HasForeignKey(d => d.ParameterId)
                .HasConstraintName("FK_Alarm_Parameter");

            entity.HasOne(d => d.ResolvedByUser).WithMany(p => p.AlarmResolvedByUsers)
                .HasForeignKey(d => d.ResolvedByUserId)
                .HasConstraintName("FK_Alarm_ResolveUser");

            entity.HasOne(d => d.Station).WithMany(p => p.Alarms)
                .HasForeignKey(d => d.StationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Alarm_Station");
        });

        modelBuilder.Entity<MfaRecoveryCode>(entity =>
        {
            entity.HasKey(x => x.MfaRecoveryCodeId);
            entity.ToTable("MfaRecoveryCode", "Security");
            entity.HasIndex(x => new { x.UserId, x.CodeHash }).IsUnique();
            entity.Property(x => x.CodeHash).IsRequired().HasMaxLength(64).IsUnicode(false);
            entity.Property(x => x.CreatedAtUtc).HasPrecision(3);
            entity.Property(x => x.UsedAtUtc).HasPrecision(3);
            entity.HasOne(x => x.User).WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity<OutboxMessage>(entity =>
        {
            entity.HasKey(x => x.OutboxMessageId);
            entity.ToTable("OutboxMessage", "Platform");
            entity.HasIndex(x => new { x.ProcessedAtUtc, x.OccurredAtUtc });
            entity.Property(x => x.EventType).IsRequired().HasMaxLength(200).IsUnicode(false);
            entity.Property(x => x.PayloadJson).IsRequired().HasColumnType("jsonb");
            entity.Property(x => x.OccurredAtUtc).HasPrecision(3);
            entity.Property(x => x.ProcessedAtUtc).HasPrecision(3);
            entity.Property(x => x.FailedAtUtc).HasPrecision(3);
            entity.Property(x => x.LastError).HasMaxLength(4000);
        });

        modelBuilder.Entity<AlarmLabel>(entity =>
        {
            entity.HasKey(e => e.AlarmLabelId);

            entity.ToTable("AlarmLabel", "Operations");

            entity.Property(e => e.Label)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.LabeledAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.Notes).HasMaxLength(1000);

            entity.HasOne(d => d.Alarm).WithMany(p => p.AlarmLabels)
                .HasForeignKey(d => d.AlarmId)
                .HasConstraintName("FK_AlarmLabel_Alarm");

            entity.HasOne(d => d.LabeledByUser).WithMany(p => p.AlarmLabels)
                .HasForeignKey(d => d.LabeledByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AlarmLabel_User");
        });

        modelBuilder.Entity<AlarmType>(entity =>
        {
            entity.HasKey(e => e.AlarmTypeId);

            entity.ToTable("AlarmType", "Operations");

            entity.HasIndex(e => e.Code, "UQ_AlarmType_Code").IsUnique();

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false);
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
        });

        modelBuilder.Entity<AnomalyEvent>(entity =>
        {
            entity.HasKey(e => e.AnomalyEventId);

            entity.ToTable("AnomalyEvent", "AI");

            entity.HasIndex(e => new { e.StationId, e.DetectedAtUtc }, "IX_Anomaly_Station_Date").IsDescending(false, true);

            entity.Property(e => e.DetectedAtUtc).HasPrecision(3);
            entity.Property(e => e.ReasonCode)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.Score).HasColumnType("decimal(9, 6)");

            entity.HasOne(d => d.MeasurementClean).WithMany(p => p.AnomalyEvents)
                .HasForeignKey(d => d.MeasurementCleanId)
                .HasConstraintName("FK_Anomaly_Measurement");

            entity.HasOne(d => d.Organization).WithMany(p => p.AnomalyEvents)
                .HasForeignKey(d => d.OrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Anomaly_Organization");

            entity.HasOne(d => d.Parameter).WithMany(p => p.AnomalyEvents)
                .HasForeignKey(d => d.ParameterId)
                .HasConstraintName("FK_Anomaly_Parameter");

            entity.HasOne(d => d.Station).WithMany(p => p.AnomalyEvents)
                .HasForeignKey(d => d.StationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Anomaly_Station");
        });

        modelBuilder.Entity<AuditLog>(entity =>
        {
            entity.HasKey(e => e.AuditLogId);

            entity.ToTable("AuditLog", "Security");

            entity.Property(e => e.ActionCode)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EntityId)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EntityType)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.IpAddress)
                .HasMaxLength(45)
                .IsUnicode(false);
            entity.Property(e => e.OccurredAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.RequestId)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Success).HasDefaultValue(true);

            entity.HasOne(d => d.ActorUser).WithMany(p => p.AuditLogs)
                .HasForeignKey(d => d.ActorUserId)
                .HasConstraintName("FK_Audit_Actor");

            entity.HasOne(d => d.Organization).WithMany(p => p.AuditLogs)
                .HasForeignKey(d => d.OrganizationId)
                .HasConstraintName("FK_Audit_Organization");
        });

        modelBuilder.Entity<ChartAnnotation>(entity =>
        {
            entity.HasKey(e => e.ChartAnnotationId);

            entity.ToTable("ChartAnnotation", "Operations");

            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.Text)
                .IsRequired()
                .HasMaxLength(2000);
            entity.Property(e => e.TimestampUtc).HasPrecision(3);
            entity.Property(e => e.UpdatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");

            entity.HasOne(d => d.Organization).WithMany(p => p.ChartAnnotations)
                .HasForeignKey(d => d.OrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Annotation_Organization");

            entity.HasOne(d => d.Parameter).WithMany(p => p.ChartAnnotations)
                .HasForeignKey(d => d.ParameterId)
                .HasConstraintName("FK_Annotation_Parameter");

            entity.HasOne(d => d.Station).WithMany(p => p.ChartAnnotations)
                .HasForeignKey(d => d.StationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Annotation_Station");

            entity.HasOne(d => d.User).WithMany(p => p.ChartAnnotations)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Annotation_User");
        });

        modelBuilder.Entity<DashboardLayout>(entity =>
        {
            entity.HasKey(e => e.DashboardLayoutId);

            entity.ToTable("DashboardLayout", "Platform");

            entity.HasIndex(e => new { e.UserId, e.LayoutName }, "UQ_DashboardLayout").IsUnique();

            entity.Property(e => e.LayoutName)
                .IsRequired()
                .HasMaxLength(100)
                .HasDefaultValue("Default");
            entity.Property(e => e.UpdatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.WidgetsJson).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.DashboardLayouts)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_DashboardLayout_User");
        });

        modelBuilder.Entity<DataQualityLog>(entity =>
        {
            entity.HasKey(e => e.DataQualityLogId);

            entity.ToTable("DataQualityLog", "Telemetry");

            entity.Property(e => e.ComputedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.InterpolatedPct).HasColumnType("decimal(7, 3)");
            entity.Property(e => e.QuarantinedPct).HasColumnType("decimal(7, 3)");
            entity.Property(e => e.RulesetVersion)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ValidPct).HasColumnType("decimal(7, 3)");
            entity.Property(e => e.WindowEndUtc).HasPrecision(3);
            entity.Property(e => e.WindowStartUtc).HasPrecision(3);

            entity.HasOne(d => d.Organization).WithMany(p => p.DataQualityLogs)
                .HasForeignKey(d => d.OrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DQ_Organization");

            entity.HasOne(d => d.Station).WithMany(p => p.DataQualityLogs)
                .HasForeignKey(d => d.StationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DQ_Station");
        });

        modelBuilder.Entity<FeatureSet>(entity =>
        {
            entity.HasKey(e => e.FeatureSetVersion);

            entity.ToTable("FeatureSet", "Telemetry");

            entity.Property(e => e.FeatureSetVersion)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.DefinitionJson).IsRequired();
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
        });

        modelBuilder.Entity<FeatureStoreEntry>(entity =>
        {
            entity.HasKey(e => e.FeatureStoreEntryId);

            entity.ToTable("FeatureStoreEntry", "Telemetry");

            entity.HasIndex(e => new { e.StationId, e.ParameterId, e.TimestampUtc, e.FeatureSetVersion }, "UX_FeatureStore_Key").IsUnique();

            entity.Property(e => e.ComputedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.FeatureSetVersion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FeaturesJson).IsRequired();
            entity.Property(e => e.SourceQualitySummary)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("VALID");
            entity.Property(e => e.TimestampUtc).HasPrecision(3);

            entity.HasOne(d => d.FeatureSetVersionNavigation).WithMany(p => p.FeatureStoreEntries)
                .HasForeignKey(d => d.FeatureSetVersion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FeatureStore_Set");

            entity.HasOne(d => d.Organization).WithMany(p => p.FeatureStoreEntries)
                .HasForeignKey(d => d.OrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FeatureStore_Organization");

            entity.HasOne(d => d.StationParameter).WithMany(p => p.FeatureStoreEntries)
                .HasForeignKey(d => new { d.StationId, d.ParameterId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FeatureStore_StationParameter");
        });

        modelBuilder.Entity<FocusStationScore>(entity =>
        {
            entity.HasKey(e => e.FocusStationScoreId);

            entity.ToTable("FocusStationScore", "AI");

            entity.Property(e => e.ComputedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.Score).HasColumnType("decimal(12, 6)");

            entity.HasOne(d => d.Organization).WithMany(p => p.FocusStationScores)
                .HasForeignKey(d => d.OrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FocusScore_Organization");

            entity.HasOne(d => d.Station).WithMany(p => p.FocusStationScores)
                .HasForeignKey(d => d.StationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FocusScore_Station");

            entity.HasOne(d => d.User).WithMany(p => p.FocusStationScores)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_FocusScore_User");
        });

        modelBuilder.Entity<IngestionBatch>(entity =>
        {
            entity.HasKey(e => e.IngestionBatchId);

            entity.ToTable("IngestionBatch", "Telemetry");

            entity.Property(e => e.IngestionBatchId).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.CompletedAtUtc).HasPrecision(3);
            entity.Property(e => e.ErrorMessage).HasMaxLength(2000);
            entity.Property(e => e.SchemaVersion)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.SourceName).HasMaxLength(200);
            entity.Property(e => e.SourceType)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("DEVICE");
            entity.Property(e => e.StartedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("RECEIVED");

            entity.HasOne(d => d.Organization).WithMany(p => p.IngestionBatches)
                .HasForeignKey(d => d.OrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_IngestionBatch_Organization");
        });

        modelBuilder.Entity<MeasurementClean>(entity =>
        {
            entity.HasKey(e => e.MeasurementCleanId);

            entity.ToTable("MeasurementClean", "Telemetry");

            entity.HasIndex(e => new { e.StationId, e.TimestampUtc }, "IX_Clean_Chart");

            entity.HasIndex(e => new { e.OrganizationId, e.TimestampUtc, e.QualityFlag }, "IX_Clean_Time");

            entity.HasIndex(e => new { e.StationId, e.ParameterId, e.TimestampUtc }, "UX_Clean_Key").IsUnique();

            entity.Property(e => e.CanonicalUnit)
                .IsRequired()
                .HasMaxLength(32)
                .IsUnicode(false);
            entity.Property(e => e.CleaningRulesetVersion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ProcessedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.QualityFlag)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("VALID");
            entity.Property(e => e.QuarantineReason)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.TimestampUtc).HasPrecision(3);
            entity.Property(e => e.Value).HasColumnType("decimal(38, 12)");

            entity.HasOne(d => d.Organization).WithMany(p => p.MeasurementCleans)
                .HasForeignKey(d => d.OrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Clean_Organization");

            entity.HasOne(d => d.SourceRaw).WithMany(p => p.MeasurementCleans)
                .HasForeignKey(d => d.SourceRawId)
                .HasConstraintName("FK_Clean_Raw");

            entity.HasOne(d => d.StationParameter).WithMany(p => p.MeasurementCleans)
                .HasForeignKey(d => new { d.StationId, d.ParameterId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Clean_StationParameter");
        });

        modelBuilder.Entity<MeasurementRaw>(entity =>
        {
            entity.HasKey(e => e.MeasurementRawId);

            entity.ToTable("MeasurementRaw", "Telemetry", tb => tb.HasTrigger("trg_MeasurementRaw_AppendOnly"));

            entity.HasIndex(e => new { e.StationId, e.ParameterId, e.DeviceTimestampUtc }, "IX_Raw_Station_Time");

            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.DeviceTimestampUtc).HasPrecision(3);
            entity.Property(e => e.IngestionTimestampUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.RawUnit)
                .HasMaxLength(32)
                .IsUnicode(false);
            entity.Property(e => e.RawValue).HasColumnType("decimal(38, 12)");

            entity.HasOne(d => d.DuplicateOf).WithMany(p => p.InverseDuplicateOf)
                .HasForeignKey(d => d.DuplicateOfId)
                .HasConstraintName("FK_Raw_Duplicate");

            entity.HasOne(d => d.IngestionBatch).WithMany(p => p.MeasurementRaws)
                .HasForeignKey(d => d.IngestionBatchId)
                .HasConstraintName("FK_Raw_Batch");

            entity.HasOne(d => d.Organization).WithMany(p => p.MeasurementRaws)
                .HasForeignKey(d => d.OrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Raw_Organization");

            entity.HasOne(d => d.StationParameter).WithMany(p => p.MeasurementRaws)
                .HasForeignKey(d => new { d.StationId, d.ParameterId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Raw_StationParameter");
        });

        modelBuilder.Entity<MlModel>(entity =>
        {
            entity.HasKey(e => e.ModelId);

            entity.ToTable("MlModel", "AI");

            entity.HasIndex(e => new { e.OrganizationId, e.ModelType, e.StationId, e.ParameterId, e.Version }, "UX_MlModel_Version").IsUnique();

            entity.Property(e => e.ModelId).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.ArtifactPath).HasMaxLength(1000);
            entity.Property(e => e.ArtifactSha256)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.CleaningRulesetVersion)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.FeatureSetVersion)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ModelType)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PromotedAtUtc).HasPrecision(3);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("TRAINING");
            entity.Property(e => e.TrainedAtUtc).HasPrecision(3);
            entity.Property(e => e.Version)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.FeatureSetVersionNavigation).WithMany(p => p.MlModels)
                .HasForeignKey(d => d.FeatureSetVersion)
                .HasConstraintName("FK_MlModel_FeatureSet");

            entity.HasOne(d => d.Organization).WithMany(p => p.MlModels)
                .HasForeignKey(d => d.OrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MlModel_Organization");

            entity.HasOne(d => d.Parameter).WithMany(p => p.MlModels)
                .HasForeignKey(d => d.ParameterId)
                .HasConstraintName("FK_MlModel_Parameter");

            entity.HasOne(d => d.Station).WithMany(p => p.MlModels)
                .HasForeignKey(d => d.StationId)
                .HasConstraintName("FK_MlModel_Station");
        });

        modelBuilder.Entity<MlTrainingRun>(entity =>
        {
            entity.HasKey(e => e.TrainingRunId);

            entity.ToTable("MlTrainingRun", "AI");

            entity.Property(e => e.TrainingRunId).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.CleaningRulesetVersion)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.DatasetEndUtc).HasPrecision(3);
            entity.Property(e => e.DatasetStartUtc).HasPrecision(3);
            entity.Property(e => e.ErrorMessage).HasMaxLength(4000);
            entity.Property(e => e.FeatureSetVersion)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FinishedAtUtc).HasPrecision(3);
            entity.Property(e => e.StartedAtUtc).HasPrecision(3);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("RUNNING");
            entity.Property(e => e.TriggerSource)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);

            entity.HasOne(d => d.FeatureSetVersionNavigation).WithMany(p => p.MlTrainingRuns)
                .HasForeignKey(d => d.FeatureSetVersion)
                .HasConstraintName("FK_TrainingRun_FeatureSet");

            entity.HasOne(d => d.Model).WithMany(p => p.MlTrainingRuns)
                .HasForeignKey(d => d.ModelId)
                .HasConstraintName("FK_TrainingRun_Model");

            entity.HasOne(d => d.Organization).WithMany(p => p.MlTrainingRuns)
                .HasForeignKey(d => d.OrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TrainingRun_Organization");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.NotificationId);

            entity.ToTable("Notification", "Operations");

            entity.HasIndex(e => new { e.UserId, e.CreatedAtUtc }, "IX_Notification_Unread")
                .IsDescending(false, true)
                .HasFilter("\"ReadAtUtc\" IS NULL");

            entity.Property(e => e.Body)
                .IsRequired()
                .HasMaxLength(2000);
            entity.Property(e => e.Channel)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("IN_APP");
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.ReadAtUtc).HasPrecision(3);
            entity.Property(e => e.SentAtUtc).HasPrecision(3);
            entity.Property(e => e.Severity)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("INFO");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(250);

            entity.HasOne(d => d.Alarm).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.AlarmId)
                .HasConstraintName("FK_Notification_Alarm");

            entity.HasOne(d => d.Organization).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.OrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Notification_Organization");

            entity.HasOne(d => d.User).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_Notification_User");
        });

        modelBuilder.Entity<NotificationPreference>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.Severity });

            entity.ToTable("NotificationPreference", "Operations");

            entity.Property(e => e.Severity)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.DesktopEnabled).HasDefaultValue(true);
            entity.Property(e => e.InAppEnabled).HasDefaultValue(true);

            entity.HasOne(d => d.User).WithMany(p => p.NotificationPreferences)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_NotificationPreference_User");
        });

        modelBuilder.Entity<Organization>(entity =>
        {
            entity.ToTable("Organization", "Platform");

            entity.HasIndex(e => e.Name, "UQ_Organization_Name").IsUnique();

            entity.HasIndex(e => e.Slug, "UQ_Organization_Slug").IsUnique();

            entity.Property(e => e.OrganizationId).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.DefaultLocale)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValue("en");
            entity.Property(e => e.DefaultTimeZone)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValue("UTC");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LogoUrl).HasMaxLength(500);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.PrimaryColor)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Slug)
                .IsRequired()
                .HasMaxLength(120)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
        });

        modelBuilder.Entity<Parameter>(entity =>
        {
            entity.HasKey(e => e.ParameterId);

            entity.ToTable("Parameter", "Core");

            entity.HasIndex(e => e.Code, "UQ_Parameter_Code").IsUnique();

            entity.Property(e => e.CanonicalUnit)
                .IsRequired()
                .HasMaxLength(32)
                .IsUnicode(false);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.DataType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("DECIMAL");
            entity.Property(e => e.DefaultResampleMinutes).HasDefaultValue(15);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.MaximumValue).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.MinimumValue).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
        });

        modelBuilder.Entity<Permission>(entity =>
        {
            entity.HasKey(e => e.PermissionId);

            entity.ToTable("Permission", "Security");

            entity.HasIndex(e => e.Code, "UQ_Permission_Code").IsUnique();

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.DisplayName)
                .IsRequired()
                .HasMaxLength(150);
        });

        modelBuilder.Entity<Region>(entity =>
        {
            entity.HasKey(e => e.RegionId);

            entity.ToTable("Region", "Core");

            entity.HasIndex(e => new { e.OrganizationId, e.Code }, "UQ_Region_Code").IsUnique();

            entity.HasIndex(e => new { e.OrganizationId, e.Name }, "UQ_Region_Name").IsUnique();

            entity.Property(e => e.RegionId).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.Organization).WithMany(p => p.Regions)
                .HasForeignKey(d => d.OrganizationId)
                .HasConstraintName("FK_Region_Organization");
        });

        modelBuilder.Entity<Report>(entity =>
        {
            entity.HasKey(e => e.ReportId);

            entity.ToTable("Report", "Reporting");

            entity.HasIndex(e => new { e.OrganizationId, e.CreatedAtUtc }, "IX_Report_Date").IsDescending(false, true);

            entity.Property(e => e.ReportId).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.CompletedAtUtc).HasPrecision(3);
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.ErrorMessage).HasMaxLength(2000);
            entity.Property(e => e.FilePath).HasMaxLength(1000);
            entity.Property(e => e.Format)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("PDF");
            entity.Property(e => e.PeriodEndUtc).HasPrecision(3);
            entity.Property(e => e.PeriodStartUtc).HasPrecision(3);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("QUEUED");

            entity.HasOne(d => d.Organization).WithMany(p => p.Reports)
                .HasForeignKey(d => d.OrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Report_Organization");

            entity.HasOne(d => d.Parameter).WithMany(p => p.Reports)
                .HasForeignKey(d => d.ParameterId)
                .HasConstraintName("FK_Report_Parameter");

            entity.HasOne(d => d.RequestedByUser).WithMany(p => p.Reports)
                .HasForeignKey(d => d.RequestedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Report_User");

            entity.HasOne(d => d.Station).WithMany(p => p.Reports)
                .HasForeignKey(d => d.StationId)
                .HasConstraintName("FK_Report_Station");
        });

        modelBuilder.Entity<ReportSchedule>(entity =>
        {
            entity.HasKey(e => e.ReportScheduleId);

            entity.ToTable("ReportSchedule", "Reporting");

            entity.Property(e => e.Format)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Frequency)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LastRunAtUtc).HasPrecision(3);
            entity.Property(e => e.NextRunAtUtc).HasPrecision(3);
            entity.Property(e => e.RecipientJson).IsRequired();

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.ReportSchedules)
                .HasForeignKey(d => d.CreatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReportSchedule_User");

            entity.HasOne(d => d.Organization).WithMany(p => p.ReportSchedules)
                .HasForeignKey(d => d.OrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReportSchedule_Organization");

            entity.HasOne(d => d.Parameter).WithMany(p => p.ReportSchedules)
                .HasForeignKey(d => d.ParameterId)
                .HasConstraintName("FK_ReportSchedule_Parameter");

            entity.HasOne(d => d.Station).WithMany(p => p.ReportSchedules)
                .HasForeignKey(d => d.StationId)
                .HasConstraintName("FK_ReportSchedule_Station");
        });

        modelBuilder.Entity<RiskScore>(entity =>
        {
            entity.HasKey(e => e.RiskScoreId);

            entity.ToTable("RiskScore", "AI");

            entity.Property(e => e.AnomalyPresence).HasColumnType("decimal(6, 3)");
            entity.Property(e => e.ComputedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.ForecastProximity).HasColumnType("decimal(6, 3)");
            entity.Property(e => e.Score).HasColumnType("decimal(6, 2)");
            entity.Property(e => e.TrendSlope).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.UpstreamPropagation).HasColumnType("decimal(6, 3)");

            entity.HasOne(d => d.Organization).WithMany(p => p.RiskScores)
                .HasForeignKey(d => d.OrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RiskScore_Organization");

            entity.HasOne(d => d.Region).WithMany(p => p.RiskScores)
                .HasForeignKey(d => d.RegionId)
                .HasConstraintName("FK_RiskScore_Region");

            entity.HasOne(d => d.Station).WithMany(p => p.RiskScores)
                .HasForeignKey(d => d.StationId)
                .HasConstraintName("FK_RiskScore_Station");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId);

            entity.ToTable("Role", "Security");

            entity.HasIndex(e => e.Code, "UQ_Role_Code").IsUnique();

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.DisplayName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.IsSystemRole).HasDefaultValue(true);

            entity.HasMany(d => d.Permissions).WithMany(p => p.Roles)
                .UsingEntity<Dictionary<string, object>>(
                    "RolePermission",
                    r => r.HasOne<Permission>().WithMany()
                        .HasForeignKey("PermissionId")
                        .HasConstraintName("FK_RolePermission_Permission"),
                    l => l.HasOne<Role>().WithMany()
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_RolePermission_Role"),
                    j =>
                    {
                        j.HasKey("RoleId", "PermissionId");
                        j.ToTable("RolePermission", "Security");
                    });
        });

        modelBuilder.Entity<Session>(entity =>
        {
            entity.HasKey(e => e.SessionId);

            entity.ToTable("Session", "Security");

            entity.HasIndex(e => e.RefreshTokenHash, "UX_Session_Token").IsUnique();

            entity.Property(e => e.SessionId).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.DeviceName).HasMaxLength(200);
            entity.Property(e => e.ExpiresAtUtc).HasPrecision(3);
            entity.Property(e => e.IpAddress)
                .HasMaxLength(45)
                .IsUnicode(false);
            entity.Property(e => e.RefreshTokenHash)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.RevokedAtUtc).HasPrecision(3);
            entity.Property(e => e.UserAgent).HasMaxLength(1000);

            entity.HasOne(d => d.User).WithMany(p => p.Sessions)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_Session_User");
        });

        modelBuilder.Entity<ShareSnapshot>(entity =>
        {
            entity.HasKey(e => e.ShareSnapshotId);

            entity.ToTable("ShareSnapshot", "Platform");

            entity.HasIndex(e => e.TokenHash, "UQ_ShareSnapshot_Token").IsUnique();

            entity.Property(e => e.ShareSnapshotId).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.ExpiresAtUtc).HasPrecision(3);
            entity.Property(e => e.RevokedAtUtc).HasPrecision(3);
            entity.Property(e => e.SnapshotJson).IsRequired();
            entity.Property(e => e.TokenHash)
                .IsRequired()
                .HasMaxLength(128)
                .IsUnicode(false);

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.ShareSnapshots)
                .HasForeignKey(d => d.CreatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ShareSnapshot_User");

            entity.HasOne(d => d.Organization).WithMany(p => p.ShareSnapshots)
                .HasForeignKey(d => d.OrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ShareSnapshot_Organization");

            entity.HasOne(d => d.Station).WithMany(p => p.ShareSnapshots)
                .HasForeignKey(d => d.StationId)
                .HasConstraintName("FK_ShareSnapshot_Station");
        });

        modelBuilder.Entity<Station>(entity =>
        {
            entity.HasKey(e => e.StationId);

            entity.ToTable("Station", "Core", tb => tb.HasTrigger("trg_Station_OrganizationConsistency"));

            entity.HasIndex(e => new { e.OrganizationId, e.Status, e.Name }, "IX_Station_Status");

            entity.HasIndex(e => new { e.OrganizationId, e.StationCode }, "UQ_Station_Code").IsUnique();

            entity.Property(e => e.StationId).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.ElevationMeters).HasColumnType("decimal(10, 3)");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LastSeenAtUtc).HasPrecision(3);
            entity.Property(e => e.Latitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.Longitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.StaffGaugeHeight).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.StationCode)
                .IsRequired()
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("OFFLINE");
            entity.Property(e => e.UpdatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");

            entity.HasOne(d => d.Organization).WithMany(p => p.Stations)
                .HasForeignKey(d => d.OrganizationId)
                .HasConstraintName("FK_Station_Organization");

            entity.HasOne(d => d.Region).WithMany(p => p.Stations)
                .HasForeignKey(d => d.RegionId)
                .HasConstraintName("FK_Station_Region");
        });

        modelBuilder.Entity<StationCluster>(entity =>
        {
            entity.HasKey(e => e.StationClusterId);

            entity.ToTable("StationCluster", "AI");

            entity.Property(e => e.AssignedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.ClusterProfile).HasMaxLength(200);

            entity.HasOne(d => d.Model).WithMany(p => p.StationClusters)
                .HasForeignKey(d => d.ModelId)
                .HasConstraintName("FK_StationCluster_Model");

            entity.HasOne(d => d.Organization).WithMany(p => p.StationClusters)
                .HasForeignKey(d => d.OrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StationCluster_Organization");

            entity.HasOne(d => d.Station).WithMany(p => p.StationClusters)
                .HasForeignKey(d => d.StationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StationCluster_Station");
        });

        modelBuilder.Entity<StationCollaborationNote>(entity =>
        {
            entity.HasKey(e => e.NoteId);

            entity.ToTable("StationCollaborationNote", "Operations");

            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.NoteText)
                .IsRequired()
                .HasMaxLength(4000);
            entity.Property(e => e.UpdatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");

            entity.HasOne(d => d.AuthorUser).WithMany(p => p.StationCollaborationNotes)
                .HasForeignKey(d => d.AuthorUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Note_Author");

            entity.HasOne(d => d.Organization).WithMany(p => p.StationCollaborationNotes)
                .HasForeignKey(d => d.OrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Note_Organization");

            entity.HasOne(d => d.ParentNote).WithMany(p => p.InverseParentNote)
                .HasForeignKey(d => d.ParentNoteId)
                .HasConstraintName("FK_Note_Parent");

            entity.HasOne(d => d.Station).WithMany(p => p.StationCollaborationNotes)
                .HasForeignKey(d => d.StationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Note_Station");
        });

        modelBuilder.Entity<StationConnection>(entity =>
        {
            entity.HasKey(e => e.StationConnectionId);

            entity.ToTable("StationConnection", "Core");

            entity.HasIndex(e => e.DeviceIdentifier, "UX_StationConnection_Device")
                .IsUnique()
                .HasFilter("\"DeviceIdentifier\" IS NOT NULL");

            entity.Property(e => e.BatteryVoltage).HasColumnType("decimal(10, 4)");
            entity.Property(e => e.DeviceIdentifier)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.FirmwareVersion)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.IsPrimary).HasDefaultValue(true);
            entity.Property(e => e.LastConnectedAtUtc).HasPrecision(3);
            entity.Property(e => e.Protocol)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.SignalStrength).HasColumnType("decimal(10, 3)");

            entity.HasOne(d => d.Station).WithMany(p => p.StationConnections)
                .HasForeignKey(d => d.StationId)
                .HasConstraintName("FK_StationConnection_Station");
        });

        modelBuilder.Entity<StationLink>(entity =>
        {
            entity.HasKey(e => e.StationLinkId);

            entity.ToTable("StationLink", "Core");

            entity.HasIndex(e => new { e.FromStationId, e.ToStationId }, "UQ_StationLink").IsUnique();

            entity.Property(e => e.DistanceMeters).HasColumnType("decimal(12, 3)");
            entity.Property(e => e.FlowDirection)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("FORWARD");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LinkType)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("DOWNSTREAM");

            entity.HasOne(d => d.FromStation).WithMany(p => p.StationLinkFromStations)
                .HasForeignKey(d => d.FromStationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StationLink_From");

            entity.HasOne(d => d.Organization).WithMany(p => p.StationLinks)
                .HasForeignKey(d => d.OrganizationId)
                .HasConstraintName("FK_StationLink_Organization");

            entity.HasOne(d => d.ToStation).WithMany(p => p.StationLinkToStations)
                .HasForeignKey(d => d.ToStationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StationLink_To");
        });

        modelBuilder.Entity<StationParameter>(entity =>
        {
            entity.HasKey(e => new { e.StationId, e.ParameterId });

            entity.ToTable("StationParameter", "Core");

            entity.Property(e => e.CalibrationOffset).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.CalibrationScale)
                .HasDefaultValue(1m)
                .HasColumnType("decimal(18, 6)");
            entity.Property(e => e.InstalledAtUtc).HasPrecision(3);
            entity.Property(e => e.IsEnabled).HasDefaultValue(true);
            entity.Property(e => e.LastCalibrationAtUtc).HasPrecision(3);
            entity.Property(e => e.SourceUnit)
                .IsRequired()
                .HasMaxLength(32)
                .IsUnicode(false);

            entity.HasOne(d => d.Parameter).WithMany(p => p.StationParameters)
                .HasForeignKey(d => d.ParameterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StationParameter_Parameter");

            entity.HasOne(d => d.Station).WithMany(p => p.StationParameters)
                .HasForeignKey(d => d.StationId)
                .HasConstraintName("FK_StationParameter_Station");
        });

        modelBuilder.Entity<SystemSetting>(entity =>
        {
            entity.HasKey(e => e.SystemSettingId);

            entity.ToTable("SystemSetting", "Platform");

            entity.HasIndex(e => new { e.OrganizationId, e.SettingKey }, "UQ_SystemSetting").IsUnique();

            entity.Property(e => e.SettingKey)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.SettingValue).IsRequired();
            entity.Property(e => e.UpdatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.ValueType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("STRING");

            entity.HasOne(d => d.Organization).WithMany(p => p.SystemSettings)
                .HasForeignKey(d => d.OrganizationId)
                .HasConstraintName("FK_SystemSetting_Organization");
        });

        modelBuilder.Entity<Threshold>(entity =>
        {
            entity.HasKey(e => e.ThresholdId);

            entity.ToTable("Threshold", "Core");

            entity.HasIndex(e => new { e.StationId, e.ParameterId, e.EffectiveFromUtc }, "IX_Threshold_Current")
                .IsDescending(false, false, true)
                .HasFilter("\"IsActive\" = TRUE");

            entity.Property(e => e.CriticalHigh).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.CriticalLow).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.EffectiveFromUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.EffectiveToUtc).HasPrecision(3);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.WarningHigh).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.WarningLow).HasColumnType("decimal(18, 6)");

            entity.HasOne(d => d.Organization).WithMany(p => p.Thresholds)
                .HasForeignKey(d => d.OrganizationId)
                .HasConstraintName("FK_Threshold_Organization");

            entity.HasOne(d => d.UpdatedByUser).WithMany(p => p.Thresholds)
                .HasForeignKey(d => d.UpdatedByUserId)
                .HasConstraintName("FK_Threshold_User");

            entity.HasOne(d => d.StationParameter).WithMany(p => p.Thresholds)
                .HasForeignKey(d => new { d.StationId, d.ParameterId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Threshold_StationParameter");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("User", "Security");

            entity.HasIndex(e => new { e.OrganizationId, e.IsActive }, "IX_User_Active");

            entity.HasIndex(e => new { e.OrganizationId, e.Email }, "UX_User_Email").IsUnique();

            entity.Property(e => e.UserId).HasDefaultValueSql("gen_random_uuid()");
            entity.Property(e => e.ClientType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("WEB");
            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");
            entity.Property(e => e.DecimalPrecision).HasDefaultValue((byte)2);
            entity.Property(e => e.DisplayName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(320)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LastLoginAtUtc).HasPrecision(3);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.PreferredLocale)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValue("en");
            entity.Property(e => e.PreferredTimeZone)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValue("UTC");
            entity.Property(e => e.RowVersion)
                .IsRequired()
                .HasColumnType("bytea")
                .IsConcurrencyToken();
            entity.Property(e => e.Theme)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("LIGHT");
            entity.Property(e => e.UpdatedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");

            entity.HasOne(d => d.Organization).WithMany(p => p.Users)
                .HasForeignKey(d => d.OrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_User_Organization");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.RoleId });

            entity.ToTable("UserRole", "Security");

            entity.Property(e => e.AssignedAtUtc)
                .HasPrecision(3)
                .HasDefaultValueSql("timezone('utc', now())");

            entity.HasOne(d => d.AssignedByUser).WithMany(p => p.UserRoleAssignedByUsers)
                .HasForeignKey(d => d.AssignedByUserId)
                .HasConstraintName("FK_UserRole_AssignedBy");

            entity.HasOne(d => d.Role).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRole_Role");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoleUsers)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_UserRole_User");
        });

        modelBuilder.Entity<VwActiveAlarm>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_ActiveAlarms", "Reporting");

            entity.Property(e => e.AcknowledgedAtUtc).HasPrecision(3);
            entity.Property(e => e.AcknowledgedBy).HasMaxLength(200);
            entity.Property(e => e.AlarmType)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false);
            entity.Property(e => e.AlarmTypeName)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Message)
                .IsRequired()
                .HasMaxLength(1000);
            entity.Property(e => e.ParameterCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.RaisedAtUtc).HasPrecision(3);
            entity.Property(e => e.RegionName).HasMaxLength(200);
            entity.Property(e => e.Severity)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.StationCode)
                .IsRequired()
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.StationName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.ThresholdValue).HasColumnType("decimal(38, 12)");
            entity.Property(e => e.ValueAtRaise).HasColumnType("decimal(38, 12)");
        });

        modelBuilder.Entity<VwCurrentTelemetry>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_CurrentTelemetry", "Reporting");

            entity.Property(e => e.CanonicalUnit)
                .IsRequired()
                .HasMaxLength(32)
                .IsUnicode(false);
            entity.Property(e => e.ParameterCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ParameterName)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.QualityFlag)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.StationCode)
                .IsRequired()
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.StationName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.TimestampUtc).HasPrecision(3);
            entity.Property(e => e.Value).HasColumnType("decimal(38, 12)");
        });

        modelBuilder.Entity<VwDataQualityLatest>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_DataQualityLatest", "Reporting");

            entity.Property(e => e.InterpolatedPct).HasColumnType("decimal(7, 3)");
            entity.Property(e => e.QuarantinedPct).HasColumnType("decimal(7, 3)");
            entity.Property(e => e.RulesetVersion)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.StationCode)
                .IsRequired()
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.StationName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.ValidPct).HasColumnType("decimal(7, 3)");
            entity.Property(e => e.WindowEndUtc).HasPrecision(3);
            entity.Property(e => e.WindowStartUtc).HasPrecision(3);
        });

        modelBuilder.Entity<VwModelHealth>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_ModelHealth", "Reporting");

            entity.Property(e => e.CleaningRulesetVersion)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FeatureSetVersion)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastTrainingFinishedAtUtc).HasPrecision(3);
            entity.Property(e => e.ModelType)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ParameterCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PromotedAtUtc).HasPrecision(3);
            entity.Property(e => e.StationCode)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.TrainedAtUtc).HasPrecision(3);
            entity.Property(e => e.Version)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<VwOrganizationKpi>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_OrganizationKpis", "Reporting");

            entity.Property(e => e.OrganizationName)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<VwStationDirectory>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_StationDirectory", "Reporting");

            entity.Property(e => e.LastSeenAtUtc).HasPrecision(3);
            entity.Property(e => e.Latitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.Longitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.OrganizationName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.RegionName).HasMaxLength(200);
            entity.Property(e => e.StationCode)
                .IsRequired()
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.StationName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<VwStationRiskLatest>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_StationRiskLatest", "Reporting");

            entity.Property(e => e.AnomalyPresence).HasColumnType("decimal(6, 3)");
            entity.Property(e => e.ComputedAtUtc).HasPrecision(3);
            entity.Property(e => e.ForecastProximity).HasColumnType("decimal(6, 3)");
            entity.Property(e => e.RegionName).HasMaxLength(200);
            entity.Property(e => e.Rn).HasColumnName("rn");
            entity.Property(e => e.Score).HasColumnType("decimal(6, 2)");
            entity.Property(e => e.StationCode)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.StationName).HasMaxLength(200);
            entity.Property(e => e.TrendSlope).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.UpstreamPropagation).HasColumnType("decimal(6, 3)");
        });

        modelBuilder.HasPostgresExtension("pgcrypto");
        modelBuilder.HasAnnotation("WaterOperations:ReportingObjectsVersion", "1");
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
