// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class AuditLog
{
    public long AuditLogId { get; set; }

    public Guid? OrganizationId { get; set; }

    public Guid? ActorUserId { get; set; }

    public string ActionCode { get; set; }

    public string EntityType { get; set; }

    public string EntityId { get; set; }

    public string RequestId { get; set; }

    public string IpAddress { get; set; }

    public bool Success { get; set; }

    public string BeforeJson { get; set; }

    public string AfterJson { get; set; }

    public string MetadataJson { get; set; }

    public DateTime OccurredAtUtc { get; set; }

    public virtual User ActorUser { get; set; }

    public virtual Organization Organization { get; set; }
}