// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class Permission
{
    public int PermissionId { get; set; }

    public string Code { get; set; }

    public string DisplayName { get; set; }

    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();
}