// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class User
{
    public Guid UserId { get; set; }

    public Guid OrganizationId { get; set; }

    public string Email { get; set; }

    public string DisplayName { get; set; }

    public string PasswordHash { get; set; }

    public string ClientType { get; set; }

    public string PreferredLocale { get; set; }

    public string PreferredTimeZone { get; set; }

    public string Theme { get; set; }

    public byte DecimalPrecision { get; set; }

    public bool IsMfaEnabled { get; set; }

    public byte[] MfaSecretEncrypted { get; set; }

    public bool IsActive { get; set; }

    public DateTime? LastLoginAtUtc { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<Alarm> AlarmAcknowledgedByUsers { get; set; } = new List<Alarm>();

    public virtual ICollection<AlarmLabel> AlarmLabels { get; set; } = new List<AlarmLabel>();

    public virtual ICollection<Alarm> AlarmResolvedByUsers { get; set; } = new List<Alarm>();

    public virtual ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();

    public virtual ICollection<ChartAnnotation> ChartAnnotations { get; set; } = new List<ChartAnnotation>();

    public virtual ICollection<DashboardLayout> DashboardLayouts { get; set; } = new List<DashboardLayout>();

    public virtual ICollection<FocusStationScore> FocusStationScores { get; set; } = new List<FocusStationScore>();

    public virtual ICollection<NotificationPreference> NotificationPreferences { get; set; } = new List<NotificationPreference>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual Organization Organization { get; set; }

    public virtual ICollection<ReportSchedule> ReportSchedules { get; set; } = new List<ReportSchedule>();

    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    public virtual ICollection<Session> Sessions { get; set; } = new List<Session>();

    public virtual ICollection<ShareSnapshot> ShareSnapshots { get; set; } = new List<ShareSnapshot>();

    public virtual ICollection<StationCollaborationNote> StationCollaborationNotes { get; set; } = new List<StationCollaborationNote>();

    public virtual ICollection<Threshold> Thresholds { get; set; } = new List<Threshold>();

    public virtual ICollection<UserRole> UserRoleAssignedByUsers { get; set; } = new List<UserRole>();

    public virtual ICollection<UserRole> UserRoleUsers { get; set; } = new List<UserRole>();
}