import { useState } from 'react';
import { stations, trend } from './data';

export function AnalyticsPage() {
  const [metric, setMetric] = useState<'level' | 'flow' | 'pressure'>('level');
  const values = metric === 'level' ? trend : metric === 'flow' ? trend.map((value) => value * 100) : trend.map((value) => value + 1.2);
  const points = values.map((value, index) => `${index * 9},${150 - (value / Math.max(...values)) * 120}`).join(' ');
  return <div className="feature-page"><div className="page-heading"><div><span className="eyebrow">TELEMETRY ANALYTICS</span><h1>Charts</h1><p>Compare typed station metrics over a selected time range.</p></div><select value={metric} onChange={(event) => setMetric(event.target.value as typeof metric)} aria-label="Metric"><option value="level">Water level</option><option value="flow">Flow rate</option><option value="pressure">Pressure</option></select></div><section className="panel"><div className="panel-heading"><h2>{metric === 'level' ? 'Water level' : metric === 'flow' ? 'Flow rate' : 'Pressure'} trend</h2><div className="segmented-control"><button className="is-selected">7 days</button><button>30 days</button><button>90 days</button></div></div><svg className="analytics-chart" viewBox="0 0 100 170" preserveAspectRatio="none" role="img" aria-label={`${metric} chart`}><polyline points={points} fill="none" stroke="var(--color-accent)" strokeWidth="1.5" vectorEffect="non-scaling-stroke" /></svg><div className="chart-axis"><span>May 10</span><span>May 13</span><span>May 16</span></div></section><div className="feature-grid"><section className="panel"><h2>Station selection</h2><div className="layer-list">{stations.slice(0, 3).map((station) => <label key={station.id}><input type="checkbox" defaultChecked /> {station.id} · {station.name}</label>)}</div></section><section className="panel"><h2>Data freshness</h2><p className="muted">All displayed values are fixture-backed and carry their source timestamp through the query boundary.</p><span className="status-badge status-badge--healthy">Updated 10:41:58 AM</span></section></div></div>;
}
