import type { Alarm, Station } from '../../types/telemetry';

export const stations: Station[] = [
  {
    id: 'ST-045',
    name: 'River Pump Station',
    district: 'Central',
    status: 'healthy',
    waterLevelMeters: 2.85,
    flowRateLitresPerSecond: 320,
    pressureBar: 4.2,
    quality: 'good',
    updatedAt: '2026-08-20T10:41:58Z',
  },
  {
    id: 'ST-078',
    name: 'North District',
    district: 'North',
    status: 'healthy',
    waterLevelMeters: 1.62,
    flowRateLitresPerSecond: 185,
    pressureBar: 2.8,
    quality: 'good',
    updatedAt: '2026-08-20T10:41:20Z',
  },
  {
    id: 'ST-031',
    name: 'Treatment Plant',
    district: 'East',
    status: 'attention',
    waterLevelMeters: 3.12,
    flowRateLitresPerSecond: 410,
    pressureBar: 5.1,
    quality: 'fair',
    updatedAt: '2026-08-20T10:40:12Z',
  },
  {
    id: 'ST-092',
    name: 'West Pipeline',
    district: 'West',
    status: 'offline',
    waterLevelMeters: 0.95,
    flowRateLitresPerSecond: 95,
    pressureBar: 1.2,
    quality: 'good',
    updatedAt: '2026-08-20T10:15:00Z',
  },
  {
    id: 'ST-110',
    name: 'South Reservoir',
    district: 'South',
    status: 'healthy',
    waterLevelMeters: 2.33,
    flowRateLitresPerSecond: 0,
    pressureBar: 3.6,
    quality: 'good',
    updatedAt: '2026-08-20T10:39:44Z',
  },
];

export const alarms: Alarm[] = [
  {
    id: 'AL-001',
    stationId: 'ST-045',
    title: 'High Water Level',
    severity: 'critical',
    message: 'Level is above the configured threshold.',
    createdAt: '2026-08-20T10:35:00Z',
    acknowledged: false,
  },
  {
    id: 'AL-002',
    stationId: 'ST-078',
    title: 'Low Pressure',
    severity: 'warning',
    message: 'Pressure is below the expected operating range.',
    createdAt: '2026-08-20T10:28:00Z',
    acknowledged: false,
  },
  {
    id: 'AL-003',
    stationId: 'ST-092',
    title: 'Sensor Disconnected',
    severity: 'warning',
    message: 'No telemetry received from this station.',
    createdAt: '2026-08-20T10:15:00Z',
    acknowledged: false,
  },
  {
    id: 'AL-004',
    stationId: 'ST-031',
    title: 'Water Quality Degraded',
    severity: 'critical',
    message: 'Quality score requires attention.',
    createdAt: '2026-08-20T09:50:00Z',
    acknowledged: false,
  },
];

export const trend = [2.8, 2.4, 3.2, 2.5, 3.4, 2.7, 3.6, 3.1, 3.8, 3.2, 3.5, 2.9];
