// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WaterOperations.Domain.Entities
{
    public partial class usp_GetUserPermissionsResult
    {
        public Guid UserId { get; set; }
        [StringLength(50)]
        public string RoleCode { get; set; }
        [StringLength(100)]
        public string PermissionCode { get; set; }
    }
}
