// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WaterOperations.Domain.Entities
{
    public partial class usp_GetStationReportStatsResult
    {
        public Guid StationId { get; set; }
        [StringLength(80)]
        public string StationCode { get; set; }
        [StringLength(200)]
        public string StationName { get; set; }
        public int ParameterId { get; set; }
        [StringLength(50)]
        public string ParameterCode { get; set; }
        public int? ReadingCount { get; set; }
        [Column("MinimumValue", TypeName = "decimal(38,12)")]
        public decimal? MinimumValue { get; set; }
        [Column("MaximumValue", TypeName = "decimal(38,12)")]
        public decimal? MaximumValue { get; set; }
        [Column("AverageValue", TypeName = "decimal(38,12)")]
        public decimal? AverageValue { get; set; }
        public int? InterpolatedCount { get; set; }
        public int? AlarmCount { get; set; }
        public int? CriticalAlarmCount { get; set; }
    }
}
