// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class Parameter
{
    public int ParameterId { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string CanonicalUnit { get; set; }

    public string DataType { get; set; }

    public decimal? MinimumValue { get; set; }

    public decimal? MaximumValue { get; set; }

    public int DefaultResampleMinutes { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Alarm> Alarms { get; set; } = new List<Alarm>();

    public virtual ICollection<AnomalyEvent> AnomalyEvents { get; set; } = new List<AnomalyEvent>();

    public virtual ICollection<ChartAnnotation> ChartAnnotations { get; set; } = new List<ChartAnnotation>();

    public virtual ICollection<MlModel> MlModels { get; set; } = new List<MlModel>();

    public virtual ICollection<ReportSchedule> ReportSchedules { get; set; } = new List<ReportSchedule>();

    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    public virtual ICollection<StationParameter> StationParameters { get; set; } = new List<StationParameter>();
}