// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class Region
{
    public Guid RegionId { get; set; }

    public Guid OrganizationId { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public string BoundaryJson { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual ICollection<RiskScore> RiskScores { get; set; } = new List<RiskScore>();

    public virtual ICollection<Station> Stations { get; set; } = new List<Station>();
}