// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class Station
{
    public Guid StationId { get; set; }

    public Guid OrganizationId { get; set; }

    public Guid? RegionId { get; set; }

    public string StationCode { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public decimal? ElevationMeters { get; set; }

    public decimal? StaffGaugeHeight { get; set; }

    public string Status { get; set; }

    public DateTime? LastSeenAtUtc { get; set; }

    public int? CommunicationIntervalSeconds { get; set; }

    public string MetadataJson { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    public virtual ICollection<Alarm> Alarms { get; set; } = new List<Alarm>();

    public virtual ICollection<AnomalyEvent> AnomalyEvents { get; set; } = new List<AnomalyEvent>();

    public virtual ICollection<ChartAnnotation> ChartAnnotations { get; set; } = new List<ChartAnnotation>();

    public virtual ICollection<DataQualityLog> DataQualityLogs { get; set; } = new List<DataQualityLog>();

    public virtual ICollection<FocusStationScore> FocusStationScores { get; set; } = new List<FocusStationScore>();

    public virtual ICollection<MlModel> MlModels { get; set; } = new List<MlModel>();

    public virtual Organization Organization { get; set; }

    public virtual Region Region { get; set; }

    public virtual ICollection<ReportSchedule> ReportSchedules { get; set; } = new List<ReportSchedule>();

    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    public virtual ICollection<RiskScore> RiskScores { get; set; } = new List<RiskScore>();

    public virtual ICollection<ShareSnapshot> ShareSnapshots { get; set; } = new List<ShareSnapshot>();

    public virtual ICollection<StationCluster> StationClusters { get; set; } = new List<StationCluster>();

    public virtual ICollection<StationCollaborationNote> StationCollaborationNotes
    {
        get;
        set;
    } = new List<StationCollaborationNote>();

    public virtual ICollection<StationConnection> StationConnections { get; set; } = new List<StationConnection>();

    public virtual ICollection<StationLink> StationLinkFromStations { get; set; } = new List<StationLink>();

    public virtual ICollection<StationLink> StationLinkToStations { get; set; } = new List<StationLink>();

    public virtual ICollection<StationParameter> StationParameters { get; set; } = new List<StationParameter>();
}
