// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class StationParameter
{
    public Guid StationId { get; set; }

    public int ParameterId { get; set; }

    public string SourceUnit { get; set; }

    public bool IsEnabled { get; set; }

    public decimal CalibrationOffset { get; set; }

    public decimal CalibrationScale { get; set; }

    public DateTime? InstalledAtUtc { get; set; }

    public DateTime? LastCalibrationAtUtc { get; set; }

    public virtual ICollection<FeatureStoreEntry> FeatureStoreEntries { get; set; } = new List<FeatureStoreEntry>();

    public virtual ICollection<MeasurementClean> MeasurementCleans { get; set; } = new List<MeasurementClean>();

    public virtual ICollection<MeasurementRaw> MeasurementRaws { get; set; } = new List<MeasurementRaw>();

    public virtual Parameter Parameter { get; set; }

    public virtual Station Station { get; set; }

    public virtual ICollection<Threshold> Thresholds { get; set; } = new List<Threshold>();
}