// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class StationLink
{
    public long StationLinkId { get; set; }

    public Guid OrganizationId { get; set; }

    public Guid FromStationId { get; set; }

    public Guid ToStationId { get; set; }

    public string LinkType { get; set; }

    public decimal? DistanceMeters { get; set; }

    public string FlowDirection { get; set; }

    public bool IsActive { get; set; }

    public virtual Station FromStation { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual Station ToStation { get; set; }
}