// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class StationConnection
{
    public long StationConnectionId { get; set; }

    public Guid StationId { get; set; }

    public string Protocol { get; set; }

    public string DeviceIdentifier { get; set; }

    public string FirmwareVersion { get; set; }

    public decimal? SignalStrength { get; set; }

    public decimal? BatteryVoltage { get; set; }

    public bool IsPrimary { get; set; }

    public bool IsActive { get; set; }

    public DateTime? LastConnectedAtUtc { get; set; }

    public virtual Station Station { get; set; }
}