// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class Threshold
{
    public long ThresholdId { get; set; }

    public Guid OrganizationId { get; set; }

    public Guid StationId { get; set; }

    public int ParameterId { get; set; }

    public decimal? WarningLow { get; set; }

    public decimal? WarningHigh { get; set; }

    public decimal? CriticalLow { get; set; }

    public decimal? CriticalHigh { get; set; }

    public DateTime EffectiveFromUtc { get; set; }

    public DateTime? EffectiveToUtc { get; set; }

    public bool IsActive { get; set; }

    public Guid? UpdatedByUserId { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual StationParameter StationParameter { get; set; }

    public virtual User UpdatedByUser { get; set; }
}