// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class AnomalyEvent
{
    public long AnomalyEventId { get; set; }

    public Guid OrganizationId { get; set; }

    public Guid StationId { get; set; }

    public int? ParameterId { get; set; }

    public long? MeasurementCleanId { get; set; }

    public string ReasonCode { get; set; }

    public decimal Score { get; set; }

    public DateTime DetectedAtUtc { get; set; }

    public int? WindowMinutes { get; set; }

    public string DetailsJson { get; set; }

    public bool IsReviewed { get; set; }

    public virtual MeasurementClean MeasurementClean { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual Parameter Parameter { get; set; }

    public virtual Station Station { get; set; }
}