// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class FocusStationScore
{
    public long FocusStationScoreId { get; set; }

    public Guid OrganizationId { get; set; }

    public Guid UserId { get; set; }

    public Guid StationId { get; set; }

    public decimal Score { get; set; }

    public int? RankNo { get; set; }

    public string ReasonsJson { get; set; }

    public DateTime ComputedAtUtc { get; set; }

    public bool IsPinned { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual Station Station { get; set; }

    public virtual User User { get; set; }
}