// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class MlModel
{
    public Guid ModelId { get; set; }

    public Guid OrganizationId { get; set; }

    public string ModelType { get; set; }

    public Guid? StationId { get; set; }

    public int? ParameterId { get; set; }

    public string Version { get; set; }

    public string Status { get; set; }

    public DateTime? TrainedAtUtc { get; set; }

    public DateTime? PromotedAtUtc { get; set; }

    public string MetricsJson { get; set; }

    public string ArtifactPath { get; set; }

    public string ArtifactSha256 { get; set; }

    public string FeatureSetVersion { get; set; }

    public string CleaningRulesetVersion { get; set; }

    public string HyperparametersJson { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual FeatureSet FeatureSetVersionNavigation { get; set; }

    public virtual ICollection<MlTrainingRun> MlTrainingRuns { get; set; } = new List<MlTrainingRun>();

    public virtual Organization Organization { get; set; }

    public virtual Parameter Parameter { get; set; }

    public virtual Station Station { get; set; }

    public virtual ICollection<StationCluster> StationClusters { get; set; } = new List<StationCluster>();
}