// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class MlTrainingRun
{
    public Guid TrainingRunId { get; set; }

    public Guid? ModelId { get; set; }

    public Guid OrganizationId { get; set; }

    public DateTime StartedAtUtc { get; set; }

    public DateTime? FinishedAtUtc { get; set; }

    public DateTime? DatasetStartUtc { get; set; }

    public DateTime? DatasetEndUtc { get; set; }

    public string FeatureSetVersion { get; set; }

    public string CleaningRulesetVersion { get; set; }

    public string TriggerSource { get; set; }

    public string Status { get; set; }

    public string MetricsJson { get; set; }

    public string ErrorMessage { get; set; }

    public long RowsRead { get; set; }

    public virtual FeatureSet FeatureSetVersionNavigation { get; set; }

    public virtual MlModel Model { get; set; }

    public virtual Organization Organization { get; set; }
}