// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class RiskScore
{
    public long RiskScoreId { get; set; }

    public Guid OrganizationId { get; set; }

    public Guid? StationId { get; set; }

    public Guid? RegionId { get; set; }

    public decimal Score { get; set; }

    public decimal? ForecastProximity { get; set; }

    public decimal? UpstreamPropagation { get; set; }

    public decimal? AnomalyPresence { get; set; }

    public decimal? TrendSlope { get; set; }

    public string WeightsJson { get; set; }

    public DateTime ComputedAtUtc { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual Region Region { get; set; }

    public virtual Station Station { get; set; }
}