// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WaterOperations.Domain.Entities;

public partial class StationCluster
{
    public long StationClusterId { get; set; }

    public Guid OrganizationId { get; set; }

    public Guid StationId { get; set; }

    public int ClusterId { get; set; }

    public string ClusterProfile { get; set; }

    public string FeatureVectorJson { get; set; }

    public DateTime AssignedAtUtc { get; set; }

    public Guid? ModelId { get; set; }

    public virtual MlModel Model { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual Station Station { get; set; }
}